# -*- coding: utf-8 -*-
"""
Created on WED Feb 12 10:07

@author: C30622B
"""

import time
import csv
import tkinter as tk
from tkinter import ttk, filedialog, messagebox
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
from bs4 import BeautifulSoup
import threading

class DealerLocatorApp:
    def __init__(self):
        self.root = tk.Tk()
        self.root.title("John Deere Dealer Locator")
        self.root.geometry("600x400")
        self.root.configure(bg="#f0f0f0")     
        self.listadecidades = [
        "25 de mayo - ARGENTINA",
        "3 de febrero - ARGENTINA",
        "a. alsina - ARGENTINA",
        "a. gonzales chaves - ARGENTINA",
        "aguas verdes - ARGENTINA",
        "alberti - ARGENTINA",
        "arrecifes - ARGENTINA",
        "ayacucho - ARGENTINA",
        "azul - ARGENTINA",
        "bahia blanca - ARGENTINA",
        "balcarce - ARGENTINA",
        "baradero - ARGENTINA",
        "benito juarez - ARGENTINA",
        "berisso - ARGENTINA",
        "bolivar - ARGENTINA",
        "bragado - ARGENTINA",
        "brandsen - ARGENTINA",
        "campana - ARGENTINA",
        "caniuelas - ARGENTINA",
        "capilla del senior - ARGENTINA",
        "capitan sarmiento - ARGENTINA",
        "carapachay - ARGENTINA",
        "carhue - ARGENTINA",
        "carilo - ARGENTINA",
        "carlos casares - ARGENTINA",
        "carlos tejedor - ARGENTINA",
        "carmen de areco - ARGENTINA",
        "carmen de patagones - ARGENTINA",
        "castelli - ARGENTINA",
        "chacabuco - ARGENTINA",
        "chascomus - ARGENTINA",
        "chivilcoy - ARGENTINA",
        "colon - ARGENTINA",
        "coronel dorrego - ARGENTINA",
        "coronel pringles - ARGENTINA",
        "coronel rosales - ARGENTINA",
        "coronel suarez - ARGENTINA",
        "costa azul - ARGENTINA",
        "costa chica - ARGENTINA",
        "costa del este - ARGENTINA",
        "costa esmeralda - ARGENTINA",
        "daireaux - ARGENTINA",
        "darregueira - ARGENTINA",
        "del viso - ARGENTINA",
        "dolores - ARGENTINA",
        "don torcuato - ARGENTINA",
        "ensenada - ARGENTINA",
        "escobar - ARGENTINA",
        "exaltacion de la cruz - ARGENTINA",
        "florentino ameghino - ARGENTINA",
        "garin - ARGENTINA",
        "gral. alvarado - ARGENTINA",
        "gral. alvear - ARGENTINA",
        "gral. arenales - ARGENTINA",
        "gral. belgrano - ARGENTINA",
        "gral. guido - ARGENTINA",
        "gral. lamadrid - ARGENTINA",
        "gral. las heras - ARGENTINA",
        "gral. lavalle - ARGENTINA",
        "gral. madariaga - ARGENTINA",
        "gral. pacheco - ARGENTINA",
        "gral. paz - ARGENTINA",
        "gral. pinto - ARGENTINA",
        "gral. pueyrredon - ARGENTINA",
        "gral. rodriguez - ARGENTINA",
        "gral. viamonte - ARGENTINA",
        "gral. villegas - ARGENTINA",
        "guamini - ARGENTINA",
        "guernica - ARGENTINA",
        "hipolito yrigoyen - ARGENTINA",
        "ing. maschwitz - ARGENTINA",
        "junin - ARGENTINA",
        "la plata - ARGENTINA",
        "laprida - ARGENTINA",
        "las flores - ARGENTINA",
        "las toninas - ARGENTINA",
        "leandro n. alem - ARGENTINA",
        "lincoln - ARGENTINA",
        "loberia - ARGENTINA",
        "lobos - ARGENTINA",
        "los cardales - ARGENTINA",
        "los toldos - ARGENTINA",
        "lucila del mar - ARGENTINA",
        "lujan - ARGENTINA",
        "magdalena - ARGENTINA",
        "maipu - ARGENTINA",
        "mar chiquita - ARGENTINA",
        "mar de ajo - ARGENTINA",
        "mar de las pampas - ARGENTINA",
        "mar del plata - ARGENTINA",
        "mar del tuyu - ARGENTINA",
        "marcos paz - ARGENTINA",
        "mercedes - ARGENTINA",
        "miramar - ARGENTINA",
        "monte - ARGENTINA",
        "monte hermoso - ARGENTINA",
        "munro - ARGENTINA",
        "navarro - ARGENTINA",
        "necochea - ARGENTINA",
        "olavarria - ARGENTINA",
        "partido de la costa - ARGENTINA",
        "pehuajo - ARGENTINA",
        "pellegrini - ARGENTINA",
        "pergamino - ARGENTINA",
        "pigue - ARGENTINA",
        "pila - ARGENTINA",
        "pilar - ARGENTINA",
        "pinamar - ARGENTINA",
        "pinar del sol - ARGENTINA",
        "polvorines - ARGENTINA",
        "pte. peron - ARGENTINA",
        "puan - ARGENTINA",
        "punta indio - ARGENTINA",
        "ramallo - ARGENTINA",
        "rauch - ARGENTINA",
        "rivadavia - ARGENTINA",
        "rojas - ARGENTINA",
        "roque perez - ARGENTINA",
        "saavedra - ARGENTINA",
        "saladillo - ARGENTINA",
        "salliquelo - ARGENTINA",
        "salto - ARGENTINA",
        "san andres de giles - ARGENTINA",
        "san antonio de areco - ARGENTINA",
        "san antonio de padua - ARGENTINA",
        "san bernardo - ARGENTINA",
        "san cayetano - ARGENTINA",
        "san clemente del tuyu - ARGENTINA",
        "san nicolas - ARGENTINA",
        "san pedro - ARGENTINA",
        "san vicente - ARGENTINA",
        "santa teresita - ARGENTINA",
        "suipacha - ARGENTINA",
        "tandil - ARGENTINA",
        "tapalque - ARGENTINA",
        "tordillo - ARGENTINA",
        "tornquist - ARGENTINA",
        "trenque lauquen - ARGENTINA",
        "tres lomas - ARGENTINA",
        "villa gesell - ARGENTINA",
        "villarino - ARGENTINA",
        "zarate - ARGENTINA",
        "11 de septiembre - ARGENTINA",
        "20 de junio - ARGENTINA",
        "25 de mayo - ARGENTINA",
        "acassuso - ARGENTINA",
        "adrogue - ARGENTINA",
        "aldo bonzi - ARGENTINA",
        "area reserva cinturon ecologico - ARGENTINA",
        "avellaneda - ARGENTINA",
        "banfield - ARGENTINA",
        "barrio parque - ARGENTINA",
        "barrio santa teresita - ARGENTINA",
        "beccar - ARGENTINA",
        "bella vista - ARGENTINA",
        "berazategui - ARGENTINA",
        "bernal este - ARGENTINA",
        "bernal oeste - ARGENTINA",
        "billinghurst - ARGENTINA",
        "boulogne - ARGENTINA",
        "burzaco - ARGENTINA",
        "carapachay - ARGENTINA",
        "caseros - ARGENTINA",
        "castelar - ARGENTINA",
        "churruca - ARGENTINA",
        "ciudad evita - ARGENTINA",
        "ciudad madero - ARGENTINA",
        "ciudadela - ARGENTINA",
        "claypole - ARGENTINA",
        "crucecita - ARGENTINA",
        "dock sud - ARGENTINA",
        "don orione - ARGENTINA",
        "el jaguel - ARGENTINA",
        "el libertador - ARGENTINA",
        "el palomar - ARGENTINA",
        "el tala - ARGENTINA",
        "el trebol - ARGENTINA",
        "ezeiza - ARGENTINA",
        "ezpeleta - ARGENTINA",
        "florencio varela - ARGENTINA",
        "florida - ARGENTINA",
        "francisco alvarez - ARGENTINA",
        "gerli - ARGENTINA",
        "glew - ARGENTINA",
        "gonzalez catan - ARGENTINA",
        "gral. lamadrid - ARGENTINA",
        "grand bourg - ARGENTINA",
        "gregorio de laferrere - ARGENTINA",
        "guillermo enrique hudson - ARGENTINA",
        "haedo - ARGENTINA",
        "hurlingham - ARGENTINA",
        "ing. sourdeaux - ARGENTINA",
        "isidro casanova - ARGENTINA",
        "ituzaingo - ARGENTINA",
        "jose c. paz - ARGENTINA",
        "jose ingenieros - ARGENTINA",
        "jose marmol - ARGENTINA",
        "la lucila - ARGENTINA",
        "la reja - ARGENTINA",
        "la tablada - ARGENTINA",
        "lanus - ARGENTINA",
        "llavallol - ARGENTINA",
        "loma hermosa - ARGENTINA",
        "lomas de zamora - ARGENTINA",
        "lomas del millon - ARGENTINA",
        "lomas del mirador - ARGENTINA",
        "longchamps - ARGENTINA",
        "los polvorines - ARGENTINA",
        "luis guillon - ARGENTINA",
        "malvinas argentinas - ARGENTINA",
        "martin coronado - ARGENTINA",
        "martinez - ARGENTINA",
        "merlo - ARGENTINA",
        "ministro rivadavia - ARGENTINA",
        "monte chingolo - ARGENTINA",
        "monte grande - ARGENTINA",
        "moreno - ARGENTINA",
        "moron - ARGENTINA",
        "muniiz - ARGENTINA",
        "olivos - ARGENTINA",
        "pablo nogues - ARGENTINA",
        "pablo podesta - ARGENTINA",
        "paso del rey - ARGENTINA",
        "pereyra - ARGENTINA",
        "platanos - ARGENTINA",
        "pontevedra - ARGENTINA",
        "quilmes - ARGENTINA",
        "rafael calzada - ARGENTINA",
        "rafael castillo - ARGENTINA",
        "ramos mejia - ARGENTINA",
        "ranelagh - ARGENTINA",
        "remedios de escalada - ARGENTINA",
        "saenz penia - ARGENTINA",
        "san antonio de padua - ARGENTINA",
        "san fernando - ARGENTINA",
        "san francisco solano - ARGENTINA",
        "san isidro - ARGENTINA",
        "san jose - ARGENTINA",
        "san justo - ARGENTINA",
        "san martin - ARGENTINA",
        "san miguel - ARGENTINA",
        "santos lugares - ARGENTINA",
        "sarandi - ARGENTINA",
        "sourigues - ARGENTINA",
        "tapiales - ARGENTINA",
        "temperley - ARGENTINA",
        "tigre - ARGENTINA",
        "tortuguitas - ARGENTINA",
        "tristan suarez - ARGENTINA",
        "trujui - ARGENTINA",
        "turdera - ARGENTINA",
        "valentin alsina - ARGENTINA",
        "vicente lopez - ARGENTINA",
        "villa adelina - ARGENTINA",
        "villa ballester - ARGENTINA",
        "villa bosch - ARGENTINA",
        "villa caraza - ARGENTINA",
        "villa celina - ARGENTINA",
        "villa centenario - ARGENTINA",
        "villa de mayo - ARGENTINA",
        "villa diamante - ARGENTINA",
        "villa dominico - ARGENTINA",
        "villa espania - ARGENTINA",
        "villa fiorito - ARGENTINA",
        "villa guillermina - ARGENTINA",
        "villa insuperable - ARGENTINA",
        "villa jose leon suarez - ARGENTINA",
        "villa la florida - ARGENTINA",
        "villa luzuriaga - ARGENTINA",
        "villa martelli - ARGENTINA",
        "villa obrera - ARGENTINA",
        "villa progreso - ARGENTINA",
        "villa raffo - ARGENTINA",
        "villa sarmiento - ARGENTINA",
        "villa tesei - ARGENTINA",
        "villa udaondo - ARGENTINA",
        "virrey del pino - ARGENTINA",
        "wilde - ARGENTINA",
        "william morris - ARGENTINA",
        "agronomia - ARGENTINA",
        "almagro - ARGENTINA",
        "balvanera - ARGENTINA",
        "barracas - ARGENTINA",
        "belgrano - ARGENTINA",
        "boca - ARGENTINA",
        "boedo - ARGENTINA",
        "caballito - ARGENTINA",
        "chacarita - ARGENTINA",
        "coghlan - ARGENTINA",
        "colegiales - ARGENTINA",
        "constitucion - ARGENTINA",
        "flores - ARGENTINA",
        "floresta - ARGENTINA",
        "la paternal - ARGENTINA",
        "liniers - ARGENTINA",
        "mataderos - ARGENTINA",
        "monserrat - ARGENTINA",
        "monte castro - ARGENTINA",
        "nueva pompeya - ARGENTINA",
        "nuniez - ARGENTINA",
        "palermo - ARGENTINA",
        "parque avellaneda - ARGENTINA",
        "parque chacabuco - ARGENTINA",
        "parque chas - ARGENTINA",
        "parque patricios - ARGENTINA",
        "puerto madero - ARGENTINA",
        "recoleta - ARGENTINA",
        "retiro - ARGENTINA",
        "saavedra - ARGENTINA",
        "san cristobal - ARGENTINA",
        "san nicolas - ARGENTINA",
        "san telmo - ARGENTINA",
        "velez sarsfield - ARGENTINA",
        "versalles - ARGENTINA",
        "villa crespo - ARGENTINA",
        "villa del parque - ARGENTINA",
        "villa devoto - ARGENTINA",
        "villa gral. mitre - ARGENTINA",
        "villa lugano - ARGENTINA",
        "villa luro - ARGENTINA",
        "villa ortuzar - ARGENTINA",
        "villa pueyrredon - ARGENTINA",
        "villa real - ARGENTINA",
        "villa riachuelo - ARGENTINA",
        "villa santa rita - ARGENTINA",
        "villa soldati - ARGENTINA",
        "villa urquiza - ARGENTINA",
        "aconquija - ARGENTINA",
        "ancasti - ARGENTINA",
        "andalgala - ARGENTINA",
        "antofagasta - ARGENTINA",
        "belen - ARGENTINA",
        "capayan - ARGENTINA",
        "capital - ARGENTINA",
        "catamarca - ARGENTINA",
        "corral quemado - ARGENTINA",
        "el alto - ARGENTINA",
        "el rodeo - ARGENTINA",
        "f.mamerto esquiu - ARGENTINA",
        "fiambala - ARGENTINA",
        "hualfin - ARGENTINA",
        "huillapima - ARGENTINA",
        "icanio - ARGENTINA",
        "la puerta - ARGENTINA",
        "las juntas - ARGENTINA",
        "londres - ARGENTINA",
        "los altos - ARGENTINA",
        "los varela - ARGENTINA",
        "mutquin - ARGENTINA",
        "paclin - ARGENTINA",
        "poman - ARGENTINA",
        "pozo de la piedra - ARGENTINA",
        "puerta de corral - ARGENTINA",
        "puerta san jose - ARGENTINA",
        "recreo - ARGENTINA",
        "s.f.v de catamarca - ARGENTINA",
        "san fernando - ARGENTINA",
        "san fernando del valle - ARGENTINA",
        "san jose - ARGENTINA",
        "santa maria - ARGENTINA",
        "santa rosa - ARGENTINA",
        "saujil - ARGENTINA",
        "tapso - ARGENTINA",
        "tinogasta - ARGENTINA",
        "valle viejo - ARGENTINA",
        "villa vil - ARGENTINA",
        "avia terai - ARGENTINA",
        "barranqueras - ARGENTINA",
        "basail - ARGENTINA",
        "campo largo - ARGENTINA",
        "capital - ARGENTINA",
        "capitan solari - ARGENTINA",
        "charadai - ARGENTINA",
        "charata - ARGENTINA",
        "chorotis - ARGENTINA",
        "ciervo petiso - ARGENTINA",
        "cnel. du graty - ARGENTINA",
        "col. benitez - ARGENTINA",
        "col. elisa - ARGENTINA",
        "col. popular - ARGENTINA",
        "colonias unidas - ARGENTINA",
        "concepcion - ARGENTINA",
        "corzuela - ARGENTINA",
        "cote lai - ARGENTINA",
        "el sauzalito - ARGENTINA",
        "enrique urien - ARGENTINA",
        "fontana - ARGENTINA",
        "fte. esperanza - ARGENTINA",
        "gancedo - ARGENTINA",
        "gral. capdevila - ARGENTINA",
        "gral. pinero - ARGENTINA",
        "gral. san martin - ARGENTINA",
        "gral. vedia - ARGENTINA",
        "hermoso campo - ARGENTINA",
        "i. del cerrito - ARGENTINA",
        "j.j. castelli - ARGENTINA",
        "la clotilde - ARGENTINA",
        "la eduvigis - ARGENTINA",
        "la escondida - ARGENTINA",
        "la leonesa - ARGENTINA",
        "la tigra - ARGENTINA",
        "la verde - ARGENTINA",
        "laguna blanca - ARGENTINA",
        "laguna limpia - ARGENTINA",
        "lapachito - ARGENTINA",
        "las brenias - ARGENTINA",
        "las garcitas - ARGENTINA",
        "las palmas - ARGENTINA",
        "los frentones - ARGENTINA",
        "machagai - ARGENTINA",
        "makalle - ARGENTINA",
        "margarita belen - ARGENTINA",
        "miraflores - ARGENTINA",
        "mision n. pompeya - ARGENTINA",
        "napenay - ARGENTINA",
        "pampa almiron - ARGENTINA",
        "pampa del indio - ARGENTINA",
        "pampa del infierno - ARGENTINA",
        "pdcia. de la plaza - ARGENTINA",
        "pdcia. roca - ARGENTINA",
        "pdcia. roque saenz penia - ARGENTINA",
        "pto. bermejo - ARGENTINA",
        "pto. eva peron - ARGENTINA",
        "puero tirol - ARGENTINA",
        "puerto vilelas - ARGENTINA",
        "quitilipi - ARGENTINA",
        "resistencia - ARGENTINA",
        "saenz penia - ARGENTINA",
        "samuhu - ARGENTINA",
        "san bernardo - ARGENTINA",
        "santa sylvina - ARGENTINA",
        "taco pozo - ARGENTINA",
        "tres isletas - ARGENTINA",
        "villa angela - ARGENTINA",
        "villa berthet - ARGENTINA",
        "villa r. bermejito - ARGENTINA",
        "aldea apeleg - ARGENTINA",
        "aldea beleiro - ARGENTINA",
        "aldea epulef - ARGENTINA",
        "alto rio sengerr - ARGENTINA",
        "buen pasto - ARGENTINA",
        "camarones - ARGENTINA",
        "carrenleufu - ARGENTINA",
        "cholila - ARGENTINA",
        "co. centinela - ARGENTINA",
        "colan conhue - ARGENTINA",
        "comodoro rivadavia - ARGENTINA",
        "corcovado - ARGENTINA",
        "cushamen - ARGENTINA",
        "dique f. ameghino - ARGENTINA",
        "dolavon - ARGENTINA",
        "dr. r. rojas - ARGENTINA",
        "el hoyo - ARGENTINA",
        "el maiten - ARGENTINA",
        "epuyen - ARGENTINA",
        "esquel - ARGENTINA",
        "facundo - ARGENTINA",
        "gaiman - ARGENTINA",
        "gan gan - ARGENTINA",
        "gastre - ARGENTINA",
        "gdor. costa - ARGENTINA",
        "gualjaina - ARGENTINA",
        "j. de san martin - ARGENTINA",
        "lago blanco - ARGENTINA",
        "lago puelo - ARGENTINA",
        "lagunita salada - ARGENTINA",
        "las plumas - ARGENTINA",
        "los altares - ARGENTINA",
        "paso de los indios - ARGENTINA",
        "paso del sapo - ARGENTINA",
        "pto. madryn - ARGENTINA",
        "pto. piramides - ARGENTINA",
        "rada tilly - ARGENTINA",
        "rawson - ARGENTINA",
        "rio mayo - ARGENTINA",
        "rio pico - ARGENTINA",
        "sarmiento - ARGENTINA",
        "tecka - ARGENTINA",
        "telsen - ARGENTINA",
        "trelew - ARGENTINA",
        "trevelin - ARGENTINA",
        "veintiocho de julio - ARGENTINA",
        "achiras - ARGENTINA",
        "adelia maria - ARGENTINA",
        "agua de oro - ARGENTINA",
        "alcira gigena - ARGENTINA",
        "aldea santa maria - ARGENTINA",
        "alejandro roca - ARGENTINA",
        "alejo ledesma - ARGENTINA",
        "alicia - ARGENTINA",
        "almafuerte - ARGENTINA",
        "alpa corral - ARGENTINA",
        "alta gracia - ARGENTINA",
        "alto alegre - ARGENTINA",
        "alto de los quebrachos - ARGENTINA",
        "altos de chipion - ARGENTINA",
        "amboy - ARGENTINA",
        "ambul - ARGENTINA",
        "ana zumaran - ARGENTINA",
        "anisacate - ARGENTINA",
        "arguello - ARGENTINA",
        "arias - ARGENTINA",
        "arroyito - ARGENTINA",
        "arroyo algodon - ARGENTINA",
        "arroyo cabral - ARGENTINA",
        "arroyo los patos - ARGENTINA",
        "assunta - ARGENTINA",
        "atahona - ARGENTINA",
        "ausonia - ARGENTINA",
        "avellaneda - ARGENTINA",
        "ballesteros - ARGENTINA",
        "ballesteros sud - ARGENTINA",
        "balnearia - ARGENTINA",
        "baniado de soto - ARGENTINA",
        "bell ville - ARGENTINA",
        "bengolea - ARGENTINA",
        "benjamin gould - ARGENTINA",
        "berrotaran - ARGENTINA",
        "bialet masse - ARGENTINA",
        "bouwer - ARGENTINA",
        "brinkmann - ARGENTINA",
        "buchardo - ARGENTINA",
        "bulnes - ARGENTINA",
        "cabalango - ARGENTINA",
        "calamuchita - ARGENTINA",
        "calchin - ARGENTINA",
        "calchin oeste - ARGENTINA",
        "calmayo - ARGENTINA",
        "camilo aldao - ARGENTINA",
        "caminiaga - ARGENTINA",
        "caniada de luque - ARGENTINA",
        "caniada de machado - ARGENTINA",
        "caniada de rio pinto - ARGENTINA",
        "caniada del sauce - ARGENTINA",
        "canals - ARGENTINA",
        "candelaria sud - ARGENTINA",
        "capilla de remedios - ARGENTINA",
        "capilla de siton - ARGENTINA",
        "capilla del carmen - ARGENTINA",
        "capilla del monte - ARGENTINA",
        "capital - ARGENTINA",
        "capitan gral b. o?higgins - ARGENTINA",
        "carnerillo - ARGENTINA",
        "carrilobo - ARGENTINA",
        "casa grande - ARGENTINA",
        "cavanagh - ARGENTINA",
        "cerro colorado - ARGENTINA",
        "chajan - ARGENTINA",
        "chalacea - ARGENTINA",
        "chaniar viejo - ARGENTINA",
        "chancani - ARGENTINA",
        "charbonier - ARGENTINA",
        "charras - ARGENTINA",
        "chazon - ARGENTINA",
        "chilibroste - ARGENTINA",
        "chucul - ARGENTINA",
        "chunia - ARGENTINA",
        "chunia huasi - ARGENTINA",
        "churqui caniada - ARGENTINA",
        "cienaga del coro - ARGENTINA",
        "cintra - ARGENTINA",
        "col. almada - ARGENTINA",
        "col. anita - ARGENTINA",
        "col. barge - ARGENTINA",
        "col. bismark - ARGENTINA",
        "col. bremen - ARGENTINA",
        "col. caroya - ARGENTINA",
        "col. italiana - ARGENTINA",
        "col. iturraspe - ARGENTINA",
        "col. las cuatro esquinas - ARGENTINA",
        "col. las pichanas - ARGENTINA",
        "col. marina - ARGENTINA",
        "col. prosperidad - ARGENTINA",
        "col. san bartolome - ARGENTINA",
        "col. san pedro - ARGENTINA",
        "col. tirolesa - ARGENTINA",
        "col. vicente aguero - ARGENTINA",
        "col. videla - ARGENTINA",
        "col. vignaud - ARGENTINA",
        "col. waltelina - ARGENTINA",
        "colazo - ARGENTINA",
        "comechingones - ARGENTINA",
        "conlara - ARGENTINA",
        "copacabana - ARGENTINA",
        "cordoba - ARGENTINA",
        "coronel baigorria - ARGENTINA",
        "coronel moldes - ARGENTINA",
        "corral de bustos - ARGENTINA",
        "corralito - ARGENTINA",
        "cosquin - ARGENTINA",
        "costa sacate - ARGENTINA",
        "cruz alta - ARGENTINA",
        "cruz de cania - ARGENTINA",
        "cruz del eje - ARGENTINA",
        "cuesta blanca - ARGENTINA",
        "dean funes - ARGENTINA",
        "del campillo - ARGENTINA",
        "despeniaderos - ARGENTINA",
        "devoto - ARGENTINA",
        "diego de rojas - ARGENTINA",
        "dique chico - ARGENTINA",
        "el araniado - ARGENTINA",
        "el brete - ARGENTINA",
        "el chacho - ARGENTINA",
        "el crispin - ARGENTINA",
        "el fortin - ARGENTINA",
        "el manzano - ARGENTINA",
        "el rastreador - ARGENTINA",
        "el rodeo - ARGENTINA",
        "el tio - ARGENTINA",
        "elena - ARGENTINA",
        "embalse - ARGENTINA",
        "esquina - ARGENTINA",
        "estacion gral. paz - ARGENTINA",
        "estacion juarez celman - ARGENTINA",
        "estancia de guadalupe - ARGENTINA",
        "estancia vieja - ARGENTINA",
        "etruria - ARGENTINA",
        "eufrasio loza - ARGENTINA",
        "falda del carmen - ARGENTINA",
        "freyre - ARGENTINA",
        "gral. baldissera - ARGENTINA",
        "gral. cabrera - ARGENTINA",
        "gral. deheza - ARGENTINA",
        "gral. fotheringham - ARGENTINA",
        "gral. levalle - ARGENTINA",
        "gral. roca - ARGENTINA",
        "guanaco muerto - ARGENTINA",
        "guasapampa - ARGENTINA",
        "guatimozin - ARGENTINA",
        "gutenberg - ARGENTINA",
        "hernando - ARGENTINA",
        "huanchillas - ARGENTINA",
        "huerta grande - ARGENTINA",
        "huinca renanco - ARGENTINA",
        "idiazabal - ARGENTINA",
        "impira - ARGENTINA",
        "inriville - ARGENTINA",
        "isla verde - ARGENTINA",
        "italo - ARGENTINA",
        "james craik - ARGENTINA",
        "jesus maria - ARGENTINA",
        "jovita - ARGENTINA",
        "justiniano posse - ARGENTINA",
        "km 658 - ARGENTINA",
        "l. v. mansilla - ARGENTINA",
        "la batea - ARGENTINA",
        "la calera - ARGENTINA",
        "la carlota - ARGENTINA",
        "la carolina - ARGENTINA",
        "la cautiva - ARGENTINA",
        "la cesira - ARGENTINA",
        "la cruz - ARGENTINA",
        "la cumbre - ARGENTINA",
        "la cumbrecita - ARGENTINA",
        "la falda - ARGENTINA",
        "la francia - ARGENTINA",
        "la granja - ARGENTINA",
        "la higuera - ARGENTINA",
        "la laguna - ARGENTINA",
        "la paisanita - ARGENTINA",
        "la palestina - ARGENTINA",
        "la pampa - ARGENTINA",
        "la paquita - ARGENTINA",
        "la para - ARGENTINA",
        "la paz - ARGENTINA",
        "la playa - ARGENTINA",
        "la playosa - ARGENTINA",
        "la poblacion - ARGENTINA",
        "la posta - ARGENTINA",
        "la puerta - ARGENTINA",
        "la quinta - ARGENTINA",
        "la rancherita - ARGENTINA",
        "la rinconada - ARGENTINA",
        "la serranita - ARGENTINA",
        "la tordilla - ARGENTINA",
        "laborde - ARGENTINA",
        "laboulaye - ARGENTINA",
        "laguna larga - ARGENTINA",
        "las acequias - ARGENTINA",
        "las albahacas - ARGENTINA",
        "las arrias - ARGENTINA",
        "las bajadas - ARGENTINA",
        "las caleras - ARGENTINA",
        "las calles - ARGENTINA",
        "las caniadas - ARGENTINA",
        "las gramillas - ARGENTINA",
        "las higueras - ARGENTINA",
        "las isletillas - ARGENTINA",
        "las junturas - ARGENTINA",
        "las palmas - ARGENTINA",
        "las penias - ARGENTINA",
        "las penias sud - ARGENTINA",
        "las perdices - ARGENTINA",
        "las playas - ARGENTINA",
        "las rabonas - ARGENTINA",
        "las saladas - ARGENTINA",
        "las tapias - ARGENTINA",
        "las varas - ARGENTINA",
        "las varillas - ARGENTINA",
        "las vertientes - ARGENTINA",
        "leguizamon - ARGENTINA",
        "leones - ARGENTINA",
        "los cedros - ARGENTINA",
        "los cerrillos - ARGENTINA",
        "los chaniaritos c.e - ARGENTINA",
        "los chanaritos r.s - ARGENTINA",
        "los cisnes - ARGENTINA",
        "los cocos - ARGENTINA",
        "los condores - ARGENTINA",
        "los hornillos - ARGENTINA",
        "los hoyos - ARGENTINA",
        "los mistoles - ARGENTINA",
        "los molinos - ARGENTINA",
        "los pozos - ARGENTINA",
        "los reartes - ARGENTINA",
        "los surgentes - ARGENTINA",
        "los talares - ARGENTINA",
        "los zorros - ARGENTINA",
        "lozada - ARGENTINA",
        "luca - ARGENTINA",
        "luque - ARGENTINA",
        "luyaba - ARGENTINA",
        "malaguenio - ARGENTINA",
        "malena - ARGENTINA",
        "malvinas argentinas - ARGENTINA",
        "manfredi - ARGENTINA",
        "maquinista gallini - ARGENTINA",
        "marcos juarez - ARGENTINA",
        "marull - ARGENTINA",
        "matorrales - ARGENTINA",
        "mattaldi - ARGENTINA",
        "mayu sumaj - ARGENTINA",
        "media naranja - ARGENTINA",
        "melo - ARGENTINA",
        "mendiolaza - ARGENTINA",
        "mi granja - ARGENTINA",
        "mina clavero - ARGENTINA",
        "miramar - ARGENTINA",
        "morrison - ARGENTINA",
        "morteros - ARGENTINA",
        "mte. buey - ARGENTINA",
        "mte. cristo - ARGENTINA",
        "mte. de los gauchos - ARGENTINA",
        "mte. lenia - ARGENTINA",
        "mte. maiz - ARGENTINA",
        "mte. ralo - ARGENTINA",
        "nicolas bruzone - ARGENTINA",
        "noetinger - ARGENTINA",
        "nono - ARGENTINA",
        "nueva cordoba - ARGENTINA",
        "obispo trejo - ARGENTINA",
        "olaeta - ARGENTINA",
        "oliva - ARGENTINA",
        "olivares san nicolas - ARGENTINA",
        "onagolty - ARGENTINA",
        "oncativo - ARGENTINA",
        "ordoniez - ARGENTINA",
        "pacheco de melo - ARGENTINA",
        "pampayasta n. - ARGENTINA",
        "pampayasta s. - ARGENTINA",
        "panaholma - ARGENTINA",
        "pascanas - ARGENTINA",
        "pasco - ARGENTINA",
        "paso del durazno - ARGENTINA",
        "paso viejo - ARGENTINA",
        "pilar - ARGENTINA",
        "pincen - ARGENTINA",
        "piquillin - ARGENTINA",
        "plaza de mercedes - ARGENTINA",
        "plaza luxardo - ARGENTINA",
        "portenia - ARGENTINA",
        "potrero de garay - ARGENTINA",
        "pozo del molle - ARGENTINA",
        "pozo nuevo - ARGENTINA",
        "pueblo italiano - ARGENTINA",
        "puesto de castro - ARGENTINA",
        "punta del agua - ARGENTINA",
        "quebracho herrado - ARGENTINA",
        "quilino - ARGENTINA",
        "rafael garcia - ARGENTINA",
        "ranqueles - ARGENTINA",
        "rayo cortado - ARGENTINA",
        "reduccion - ARGENTINA",
        "rincon - ARGENTINA",
        "rio bamba - ARGENTINA",
        "rio ceballos - ARGENTINA",
        "rio cuarto - ARGENTINA",
        "rio de los sauces - ARGENTINA",
        "rio primero - ARGENTINA",
        "rio segundo - ARGENTINA",
        "rio tercero - ARGENTINA",
        "rosales - ARGENTINA",
        "rosario del saladillo - ARGENTINA",
        "sacanta - ARGENTINA",
        "sagrada familia - ARGENTINA",
        "saira - ARGENTINA",
        "saladillo - ARGENTINA",
        "saldan - ARGENTINA",
        "salsacate - ARGENTINA",
        "salsipuedes - ARGENTINA",
        "sampacho - ARGENTINA",
        "san agustin - ARGENTINA",
        "san antonio de arredondo - ARGENTINA",
        "san antonio de litin - ARGENTINA",
        "san basilio - ARGENTINA",
        "san carlos minas - ARGENTINA",
        "san clemente - ARGENTINA",
        "san esteban - ARGENTINA",
        "san francisco - ARGENTINA",
        "san ignacio - ARGENTINA",
        "san javier - ARGENTINA",
        "san jeronimo - ARGENTINA",
        "san joaquin - ARGENTINA",
        "san jose de la dormida - ARGENTINA",
        "san jose de las salinas - ARGENTINA",
        "san lorenzo - ARGENTINA",
        "san marcos sierras - ARGENTINA",
        "san marcos sud - ARGENTINA",
        "san pedro - ARGENTINA",
        "san pedro n. - ARGENTINA",
        "san roque - ARGENTINA",
        "san vicente - ARGENTINA",
        "santa catalina - ARGENTINA",
        "santa elena - ARGENTINA",
        "santa eufemia - ARGENTINA",
        "santa maria - ARGENTINA",
        "sarmiento - ARGENTINA",
        "saturnino m.laspiur - ARGENTINA",
        "sauce arriba - ARGENTINA",
        "sebastian elcano - ARGENTINA",
        "seeber - ARGENTINA",
        "segunda usina - ARGENTINA",
        "serrano - ARGENTINA",
        "serrezuela - ARGENTINA",
        "sgo. temple - ARGENTINA",
        "silvio pellico - ARGENTINA",
        "simbolar - ARGENTINA",
        "sinsacate - ARGENTINA",
        "sta. rosa de calamuchita - ARGENTINA",
        "sta. rosa de rio primero - ARGENTINA",
        "suco - ARGENTINA",
        "tala caniada - ARGENTINA",
        "tala huasi - ARGENTINA",
        "talaini - ARGENTINA",
        "tancacha - ARGENTINA",
        "tanti - ARGENTINA",
        "ticino - ARGENTINA",
        "tinoco - ARGENTINA",
        "tio pujio - ARGENTINA",
        "toledo - ARGENTINA",
        "toro pujio - ARGENTINA",
        "tosno - ARGENTINA",
        "tosquita - ARGENTINA",
        "transito - ARGENTINA",
        "tuclame - ARGENTINA",
        "tutti - ARGENTINA",
        "ucacha - ARGENTINA",
        "unquillo - ARGENTINA",
        "valle de anisacate - ARGENTINA",
        "valle hermoso - ARGENTINA",
        "velez sarfield - ARGENTINA",
        "viamonte - ARGENTINA",
        "vicunia mackenna - ARGENTINA",
        "villa allende - ARGENTINA",
        "villa amancay - ARGENTINA",
        "villa ascasubi - ARGENTINA",
        "villa candelaria n. - ARGENTINA",
        "villa carlos paz - ARGENTINA",
        "villa cerro azul - ARGENTINA",
        "villa ciudad de america - ARGENTINA",
        "villa ciudad pque los reartes - ARGENTINA",
        "villa concepcion del tio - ARGENTINA",
        "villa cura brochero - ARGENTINA",
        "villa de las rosas - ARGENTINA",
        "villa de maria - ARGENTINA",
        "villa de pocho - ARGENTINA",
        "villa de soto - ARGENTINA",
        "villa del dique - ARGENTINA",
        "villa del prado - ARGENTINA",
        "villa del rosario - ARGENTINA",
        "villa del totoral - ARGENTINA",
        "villa dolores - ARGENTINA",
        "villa el chancay - ARGENTINA",
        "villa elisa - ARGENTINA",
        "villa flor serrana - ARGENTINA",
        "villa fontana - ARGENTINA",
        "villa giardino - ARGENTINA",
        "villa gral. belgrano - ARGENTINA",
        "villa gutierrez - ARGENTINA",
        "villa huidobro - ARGENTINA",
        "villa la bolsa - ARGENTINA",
        "villa los aromos - ARGENTINA",
        "villa los patos - ARGENTINA",
        "villa maria - ARGENTINA",
        "villa nueva - ARGENTINA",
        "villa pque. santa ana - ARGENTINA",
        "villa pque. siquiman - ARGENTINA",
        "villa quillinzo - ARGENTINA",
        "villa rossi - ARGENTINA",
        "villa rumipal - ARGENTINA",
        "villa san esteban - ARGENTINA",
        "villa san isidro - ARGENTINA",
        "villa santa cruz - ARGENTINA",
        "villa sarmiento g.r - ARGENTINA",
        "villa sarmiento s.a - ARGENTINA",
        "villa tulumba - ARGENTINA",
        "villa valeria - ARGENTINA",
        "villa yacanto - ARGENTINA",
        "washington - ARGENTINA",
        "wenceslao escalante - ARGENTINA",
        "ycho cruz sierras - ARGENTINA",
        "alvear - ARGENTINA",
        "bella vista - ARGENTINA",
        "beron de astrada - ARGENTINA",
        "bonpland - ARGENTINA",
        "caa cati - ARGENTINA",
        "capital - ARGENTINA",
        "chavarria - ARGENTINA",
        "col. c. pellegrini - ARGENTINA",
        "col. libertad - ARGENTINA",
        "col. liebig - ARGENTINA",
        "col. sta rosa - ARGENTINA",
        "concepcion - ARGENTINA",
        "cruz de los milagros - ARGENTINA",
        "curuzu-cuatia - ARGENTINA",
        "empedrado - ARGENTINA",
        "esquina - ARGENTINA",
        "estacion torrent - ARGENTINA",
        "felipe yofre - ARGENTINA",
        "garruchos - ARGENTINA",
        "gdor. agronomo - ARGENTINA",
        "gdor. martinez - ARGENTINA",
        "goya - ARGENTINA",
        "guaviravi - ARGENTINA",
        "herlitzka - ARGENTINA",
        "ita-ibate - ARGENTINA",
        "itati - ARGENTINA",
        "ituzaingo - ARGENTINA",
        "jose rafael gomez - ARGENTINA",
        "juan pujol - ARGENTINA",
        "la cruz - ARGENTINA",
        "lavalle - ARGENTINA",
        "lomas de vallejos - ARGENTINA",
        "loreto - ARGENTINA",
        "mariano i. loza - ARGENTINA",
        "mburucuya - ARGENTINA",
        "mercedes - ARGENTINA",
        "mocoreta - ARGENTINA",
        "mte. caseros - ARGENTINA",
        "nueve de julio - ARGENTINA",
        "palmar grande - ARGENTINA",
        "parada pucheta - ARGENTINA",
        "paso de la patria - ARGENTINA",
        "paso de los libres - ARGENTINA",
        "pedro r. fernandez - ARGENTINA",
        "perugorria - ARGENTINA",
        "pueblo libertador - ARGENTINA",
        "ramada paso - ARGENTINA",
        "riachuelo - ARGENTINA",
        "saladas - ARGENTINA",
        "san antonio - ARGENTINA",
        "san carlos - ARGENTINA",
        "san cosme - ARGENTINA",
        "san lorenzo - ARGENTINA",
        "san luis del palmar - ARGENTINA",
        "san miguel - ARGENTINA",
        "san roque - ARGENTINA",
        "santa ana - ARGENTINA",
        "santa lucia - ARGENTINA",
        "santo tome - ARGENTINA",
        "sauce - ARGENTINA",
        "tabay - ARGENTINA",
        "tapebicua - ARGENTINA",
        "tatacua - ARGENTINA",
        "virasoro - ARGENTINA",
        "yapeyu - ARGENTINA",
        "yataiti calle - ARGENTINA",
        "alarcon - ARGENTINA",
        "alcaraz - ARGENTINA",
        "alcaraz n. - ARGENTINA",
        "alcaraz s. - ARGENTINA",
        "aldea asuncion - ARGENTINA",
        "aldea brasilera - ARGENTINA",
        "aldea elgenfeld - ARGENTINA",
        "aldea grapschental - ARGENTINA",
        "aldea ma. luisa - ARGENTINA",
        "aldea protestante - ARGENTINA",
        "aldea salto - ARGENTINA",
        "aldea san antonio g - ARGENTINA",
        "aldea san antonio p - ARGENTINA",
        "aldea san juan - ARGENTINA",
        "aldea san miguel - ARGENTINA",
        "aldea san rafael - ARGENTINA",
        "aldea spatzenkutter - ARGENTINA",
        "aldea sta. maria - ARGENTINA",
        "aldea sta. rosa - ARGENTINA",
        "aldea valle maria - ARGENTINA",
        "altamirano sur - ARGENTINA",
        "antelo - ARGENTINA",
        "antonio tomas - ARGENTINA",
        "aranguren - ARGENTINA",
        "arroyo baru - ARGENTINA",
        "arroyo burgos - ARGENTINA",
        "arroyo cle - ARGENTINA",
        "arroyo corralito - ARGENTINA",
        "arroyo del medio - ARGENTINA",
        "arroyo maturrango - ARGENTINA",
        "arroyo palo seco - ARGENTINA",
        "banderas - ARGENTINA",
        "basavilbaso - ARGENTINA",
        "betbeder - ARGENTINA",
        "bovril - ARGENTINA",
        "caseros - ARGENTINA",
        "ceibas - ARGENTINA",
        "cerrito - ARGENTINA",
        "chajari - ARGENTINA",
        "chilcas - ARGENTINA",
        "clodomiro ledesma - ARGENTINA",
        "col. alemana - ARGENTINA",
        "col. avellaneda - ARGENTINA",
        "col. avigdor - ARGENTINA",
        "col. ayui - ARGENTINA",
        "col. baylina - ARGENTINA",
        "col. carrasco - ARGENTINA",
        "col. celina - ARGENTINA",
        "col. cerrito - ARGENTINA",
        "col. crespo - ARGENTINA",
        "col. elia - ARGENTINA",
        "col. ensayo - ARGENTINA",
        "col. gral. roca - ARGENTINA",
        "col. la argentina - ARGENTINA",
        "col. merou - ARGENTINA",
        "col. oficial nf3 - ARGENTINA",
        "col. oficial n 13 - ARGENTINA",
        "col. oficial n 14 - ARGENTINA",
        "col. oficial n5 - ARGENTINA",
        "col. reffino - ARGENTINA",
        "col. tunas - ARGENTINA",
        "col. viraro - ARGENTINA",
        "colon - ARGENTINA",
        "concepcion del uruguay - ARGENTINA",
        "concordia - ARGENTINA",
        "conscripto bernardi - ARGENTINA",
        "costa grande - ARGENTINA",
        "costa san antonio - ARGENTINA",
        "costa uruguay n. - ARGENTINA",
        "costa uruguay s. - ARGENTINA",
        "crespo - ARGENTINA",
        "crucecitas 3 - ARGENTINA",
        "crucecitas 7 - ARGENTINA",
        "crucecitas 8 - ARGENTINA",
        "cuchilla redonda - ARGENTINA",
        "curtiembre - ARGENTINA",
        "diamante - ARGENTINA",
        "distrito 6 - ARGENTINA",
        "distrito chaniar - ARGENTINA",
        "distrito chiqueros - ARGENTINA",
        "distrito cuarto - ARGENTINA",
        "distrito diego lopez - ARGENTINA",
        "distrito pajonal - ARGENTINA",
        "distrito sauce - ARGENTINA",
        "distrito tala - ARGENTINA",
        "distrito talitas - ARGENTINA",
        "don cristobal 1 seccion - ARGENTINA",
        "don cristobal 2 seccion - ARGENTINA",
        "durazno - ARGENTINA",
        "el cimarron - ARGENTINA",
        "el gramillal - ARGENTINA",
        "el palenque - ARGENTINA",
        "el pingo - ARGENTINA",
        "el quebracho - ARGENTINA",
        "el redomon - ARGENTINA",
        "el solar - ARGENTINA",
        "enrique carbo - ARGENTINA",
        "entre rios - ARGENTINA",
        "espinillo n. - ARGENTINA",
        "estacion campos - ARGENTINA",
        "estacion escrinia - ARGENTINA",
        "estacion lazo - ARGENTINA",
        "estacion raices - ARGENTINA",
        "estacion yerua - ARGENTINA",
        "estancia grande - ARGENTINA",
        "estancia libaros - ARGENTINA",
        "estancia racedo - ARGENTINA",
        "estancia sola - ARGENTINA",
        "estancia yuqueri - ARGENTINA",
        "estaquitas - ARGENTINA",
        "faustino m. parera - ARGENTINA",
        "febre - ARGENTINA",
        "federacion - ARGENTINA",
        "federal - ARGENTINA",
        "gdor. echague - ARGENTINA",
        "gdor. mansilla - ARGENTINA",
        "gilbert - ARGENTINA",
        "gonzalez calderon - ARGENTINA",
        "gral. almada - ARGENTINA",
        "gral. alvear - ARGENTINA",
        "gral. campos - ARGENTINA",
        "gral. galarza - ARGENTINA",
        "gral. ramirez - ARGENTINA",
        "gualeguay - ARGENTINA",
        "gualeguaychu - ARGENTINA",
        "gualeguaycito - ARGENTINA",
        "guardamonte - ARGENTINA",
        "hambis - ARGENTINA",
        "hasenkamp - ARGENTINA",
        "hernandarias - ARGENTINA",
        "hernandez - ARGENTINA",
        "herrera - ARGENTINA",
        "hinojal - ARGENTINA",
        "hocker - ARGENTINA",
        "ing. sajaroff - ARGENTINA",
        "irazusta - ARGENTINA",
        "isletas - ARGENTINA",
        "j.j de urquiza - ARGENTINA",
        "jubileo - ARGENTINA",
        "la clarita - ARGENTINA",
        "la criolla - ARGENTINA",
        "la esmeralda - ARGENTINA",
        "la florida - ARGENTINA",
        "la fraternidad - ARGENTINA",
        "la hierra - ARGENTINA",
        "la ollita - ARGENTINA",
        "la paz - ARGENTINA",
        "la picada - ARGENTINA",
        "la providencia - ARGENTINA",
        "la verbena - ARGENTINA",
        "laguna benitez - ARGENTINA",
        "larroque - ARGENTINA",
        "las cuevas - ARGENTINA",
        "las garzas - ARGENTINA",
        "las guachas - ARGENTINA",
        "las mercedes - ARGENTINA",
        "las moscas - ARGENTINA",
        "las mulitas - ARGENTINA",
        "las toscas - ARGENTINA",
        "laurencena - ARGENTINA",
        "libertador san martin - ARGENTINA",
        "loma limpia - ARGENTINA",
        "los ceibos - ARGENTINA",
        "los charruas - ARGENTINA",
        "los conquistadores - ARGENTINA",
        "lucas gonzalez - ARGENTINA",
        "lucas n. - ARGENTINA",
        "lucas s. 1 - ARGENTINA",
        "lucas s. 2 - ARGENTINA",
        "macia - ARGENTINA",
        "maria grande - ARGENTINA",
        "maria grande 2 - ARGENTINA",
        "medanos - ARGENTINA",
        "mojones n. - ARGENTINA",
        "mojones s. - ARGENTINA",
        "molino doll - ARGENTINA",
        "monte redondo - ARGENTINA",
        "montoya - ARGENTINA",
        "mulas grandes - ARGENTINA",
        "niancay - ARGENTINA",
        "nogoya - ARGENTINA",
        "nueva escocia - ARGENTINA",
        "nueva vizcaya - ARGENTINA",
        "ombu - ARGENTINA",
        "oro verde - ARGENTINA",
        "parana - ARGENTINA",
        "pasaje guayaquil - ARGENTINA",
        "pasaje las tunas - ARGENTINA",
        "paso de la arena - ARGENTINA",
        "paso de la laguna - ARGENTINA",
        "paso de las piedras - ARGENTINA",
        "paso duarte - ARGENTINA",
        "pastor britos - ARGENTINA",
        "pedernal - ARGENTINA",
        "perdices - ARGENTINA",
        "picada beron - ARGENTINA",
        "piedras blancas - ARGENTINA",
        "primer distrito cuchilla - ARGENTINA",
        "primero de mayo - ARGENTINA",
        "pronunciamiento - ARGENTINA",
        "pto. algarrobo - ARGENTINA",
        "pto. ibicuy - ARGENTINA",
        "pueblo brugo - ARGENTINA",
        "pueblo cazes - ARGENTINA",
        "pueblo gral. belgrano - ARGENTINA",
        "pueblo liebig - ARGENTINA",
        "puerto yerua - ARGENTINA",
        "punta del monte - ARGENTINA",
        "quebracho - ARGENTINA",
        "quinto distrito - ARGENTINA",
        "raices oeste - ARGENTINA",
        "rincon de nogoya - ARGENTINA",
        "rincon del cinto - ARGENTINA",
        "rincon del doll - ARGENTINA",
        "rincon del gato - ARGENTINA",
        "rocamora - ARGENTINA",
        "rosario del tala - ARGENTINA",
        "san benito - ARGENTINA",
        "san cipriano - ARGENTINA",
        "san ernesto - ARGENTINA",
        "san gustavo - ARGENTINA",
        "san jaime - ARGENTINA",
        "san jose - ARGENTINA",
        "san jose de feliciano - ARGENTINA",
        "san justo - ARGENTINA",
        "san marcial - ARGENTINA",
        "san pedro - ARGENTINA",
        "san ramirez - ARGENTINA",
        "san ramon - ARGENTINA",
        "san roque - ARGENTINA",
        "san salvador - ARGENTINA",
        "san victor - ARGENTINA",
        "santa ana - ARGENTINA",
        "santa anita - ARGENTINA",
        "santa elena - ARGENTINA",
        "santa lucia - ARGENTINA",
        "santa luisa - ARGENTINA",
        "sauce de luna - ARGENTINA",
        "sauce montrull - ARGENTINA",
        "sauce pinto - ARGENTINA",
        "sauce sur - ARGENTINA",
        "segui - ARGENTINA",
        "sir leonard - ARGENTINA",
        "sosa - ARGENTINA",
        "tabossi - ARGENTINA",
        "tezanos pinto - ARGENTINA",
        "ubajay - ARGENTINA",
        "urdinarrain - ARGENTINA",
        "veinte de septiembre - ARGENTINA",
        "viale - ARGENTINA",
        "victoria - ARGENTINA",
        "villa clara - ARGENTINA",
        "villa del rosario - ARGENTINA",
        "villa dominguez - ARGENTINA",
        "villa elisa - ARGENTINA",
        "villa fontana - ARGENTINA",
        "villa gdor. etchevehere - ARGENTINA",
        "villa mantero - ARGENTINA",
        "villa paranacito - ARGENTINA",
        "villa urquiza - ARGENTINA",
        "villaguay - ARGENTINA",
        "walter moss - ARGENTINA",
        "yacare - ARGENTINA",
        "yeso oeste - ARGENTINA",
        "buena vista - ARGENTINA",
        "clorinda - ARGENTINA",
        "col. pastoril - ARGENTINA",
        "cte. fontana - ARGENTINA",
        "el colorado - ARGENTINA",
        "el espinillo - ARGENTINA",
        "estanislao del campo - ARGENTINA",
        "formosa - ARGENTINA",
        "fortin lugones - ARGENTINA",
        "gral. lucio v. mansilla - ARGENTINA",
        "gral. manuel belgrano - ARGENTINA",
        "gral. mosconi - ARGENTINA",
        "gran guardia - ARGENTINA",
        "herradura - ARGENTINA",
        "ibarreta - ARGENTINA",
        "ing. juarez - ARGENTINA",
        "laguna blanca - ARGENTINA",
        "laguna naick neck - ARGENTINA",
        "laguna yema - ARGENTINA",
        "las lomitas - ARGENTINA",
        "los chiriguanos - ARGENTINA",
        "mayor v. villafanie - ARGENTINA",
        "mision san fco. - ARGENTINA",
        "palo santo - ARGENTINA",
        "pirane - ARGENTINA",
        "pozo del maza - ARGENTINA",
        "riacho he-he - ARGENTINA",
        "san hilario - ARGENTINA",
        "san martin ii - ARGENTINA",
        "siete palmas - ARGENTINA",
        "subteniente perin - ARGENTINA",
        "tres lagunas - ARGENTINA",
        "villa dos trece - ARGENTINA",
        "villa escolar - ARGENTINA",
        "villa gral. guemes - ARGENTINA",
        "abdon castro tolay - ARGENTINA",
        "abra pampa - ARGENTINA",
        "abralaite - ARGENTINA",
        "aguas calientes - ARGENTINA",
        "arrayanal - ARGENTINA",
        "barrios - ARGENTINA",
        "caimancito - ARGENTINA",
        "calilegua - ARGENTINA",
        "cangrejillos - ARGENTINA",
        "caspala - ARGENTINA",
        "catua - ARGENTINA",
        "cieneguillas - ARGENTINA",
        "coranzulli - ARGENTINA",
        "cusi-cusi - ARGENTINA",
        "el aguilar - ARGENTINA",
        "el carmen - ARGENTINA",
        "el condor - ARGENTINA",
        "el fuerte - ARGENTINA",
        "el piquete - ARGENTINA",
        "el talar - ARGENTINA",
        "fraile pintado - ARGENTINA",
        "hipolito yrigoyen - ARGENTINA",
        "huacalera - ARGENTINA",
        "humahuaca - ARGENTINA",
        "la esperanza - ARGENTINA",
        "la mendieta - ARGENTINA",
        "la quiaca - ARGENTINA",
        "ledesma - ARGENTINA",
        "libertador gral. san martin - ARGENTINA",
        "maimara - ARGENTINA",
        "mina pirquitas - ARGENTINA",
        "monterrico - ARGENTINA",
        "palma sola - ARGENTINA",
        "palpala - ARGENTINA",
        "pampa blanca - ARGENTINA",
        "pampichuela - ARGENTINA",
        "perico - ARGENTINA",
        "puesto del marques - ARGENTINA",
        "puesto viejo - ARGENTINA",
        "pumahuasi - ARGENTINA",
        "purmamarca - ARGENTINA",
        "rinconada - ARGENTINA",
        "rodeitos - ARGENTINA",
        "rosario de rio grande - ARGENTINA",
        "san antonio - ARGENTINA",
        "san francisco - ARGENTINA",
        "san pedro - ARGENTINA",
        "san rafael - ARGENTINA",
        "san salvador - ARGENTINA",
        "santa ana - ARGENTINA",
        "santa catalina - ARGENTINA",
        "santa clara - ARGENTINA",
        "susques - ARGENTINA",
        "tilcara - ARGENTINA",
        "tres cruces - ARGENTINA",
        "tumbaya - ARGENTINA",
        "valle grande - ARGENTINA",
        "vinalito - ARGENTINA",
        "volcan - ARGENTINA",
        "yala - ARGENTINA",
        "yavi - ARGENTINA",
        "yuto - ARGENTINA",
        "abramo - ARGENTINA",
        "adolfo van praet - ARGENTINA",
        "agustoni - ARGENTINA",
        "algarrobo del aguila - ARGENTINA",
        "alpachiri - ARGENTINA",
        "alta italia - ARGENTINA",
        "anguil - ARGENTINA",
        "arata - ARGENTINA",
        "ataliva roca - ARGENTINA",
        "bernardo larroude - ARGENTINA",
        "bernasconi - ARGENTINA",
        "caleufu - ARGENTINA",
        "carro quemado - ARGENTINA",
        "catrilo - ARGENTINA",
        "ceballos - ARGENTINA",
        "chacharramendi - ARGENTINA",
        "col. baron - ARGENTINA",
        "col. santa maria - ARGENTINA",
        "conhelo - ARGENTINA",
        "coronel hilario lagos - ARGENTINA",
        "cuchillo-co - ARGENTINA",
        "doblas - ARGENTINA",
        "dorila - ARGENTINA",
        "eduardo castex - ARGENTINA",
        "embajador martini - ARGENTINA",
        "falucho - ARGENTINA",
        "gral. acha - ARGENTINA",
        "gral. manuel campos - ARGENTINA",
        "gral. pico - ARGENTINA",
        "guatrache - ARGENTINA",
        "ing. luiggi - ARGENTINA",
        "intendente alvear - ARGENTINA",
        "jacinto arauz - ARGENTINA",
        "la adela - ARGENTINA",
        "la humada - ARGENTINA",
        "la maruja - ARGENTINA",
        "la pampa - ARGENTINA",
        "la reforma - ARGENTINA",
        "limay mahuida - ARGENTINA",
        "lonquimay - ARGENTINA",
        "loventuel - ARGENTINA",
        "luan toro - ARGENTINA",
        "macachin - ARGENTINA",
        "maisonnave - ARGENTINA",
        "mauricio mayer - ARGENTINA",
        "metileo - ARGENTINA",
        "miguel cane - ARGENTINA",
        "miguel riglos - ARGENTINA",
        "monte nievas - ARGENTINA",
        "parera - ARGENTINA",
        "peru - ARGENTINA",
        "pichi-huinca - ARGENTINA",
        "puelches - ARGENTINA",
        "puelen - ARGENTINA",
        "quehue - ARGENTINA",
        "quemu quemu - ARGENTINA",
        "quetrequen - ARGENTINA",
        "rancul - ARGENTINA",
        "realico - ARGENTINA",
        "relmo - ARGENTINA",
        "rolon - ARGENTINA",
        "rucanelo - ARGENTINA",
        "sarah - ARGENTINA",
        "speluzzi - ARGENTINA",
        "sta. isabel - ARGENTINA",
        "sta. rosa - ARGENTINA",
        "sta. teresa - ARGENTINA",
        "telen - ARGENTINA",
        "toay - ARGENTINA",
        "tomas m. de anchorena - ARGENTINA",
        "trenel - ARGENTINA",
        "unanue - ARGENTINA",
        "uriburu - ARGENTINA",
        "veinticinco de mayo - ARGENTINA",
        "vertiz - ARGENTINA",
        "victorica - ARGENTINA",
        "villa mirasol - ARGENTINA",
        "winifreda - ARGENTINA",
        "arauco - ARGENTINA",
        "capital - ARGENTINA",
        "castro barros - ARGENTINA",
        "chamical - ARGENTINA",
        "chilecito - ARGENTINA",
        "coronel f. varela - ARGENTINA",
        "famatina - ARGENTINA",
        "gral. a.v.penialoza - ARGENTINA",
        "gral. belgrano - ARGENTINA",
        "gral. j.f. quiroga - ARGENTINA",
        "gral. lamadrid - ARGENTINA",
        "gral. ocampo - ARGENTINA",
        "gral. san martin - ARGENTINA",
        "independencia - ARGENTINA",
        "rosario penaloza - ARGENTINA",
        "san blas de los sauces - ARGENTINA",
        "sanagasta - ARGENTINA",
        "vinchina - ARGENTINA",
        "capital - ARGENTINA",
        "chacras de coria - ARGENTINA",
        "dorrego - ARGENTINA",
        "gllen - ARGENTINA",
        "godoy cruz - ARGENTINA",
        "gral. alvear - ARGENTINA",
        "guaymallen - ARGENTINA",
        "junin - ARGENTINA",
        "la paz - ARGENTINA",
        "las heras - ARGENTINA",
        "lavalle - ARGENTINA",
        "lujan - ARGENTINA",
        "lujan de cuyo - ARGENTINA",
        "maipu - ARGENTINA",
        "malargue - ARGENTINA",
        "rivadavia - ARGENTINA",
        "san carlos - ARGENTINA",
        "san martin - ARGENTINA",
        "san rafael - ARGENTINA",
        "sta. rosa - ARGENTINA",
        "tunuyan - ARGENTINA",
        "tupungato - ARGENTINA",
        "villa nueva - ARGENTINA",
        "alba posse - ARGENTINA",
        "almafuerte - ARGENTINA",
        "apostoles - ARGENTINA",
        "aristobulo del valle - ARGENTINA",
        "arroyo del medio - ARGENTINA",
        "azara - ARGENTINA",
        "bdo. de irigoyen - ARGENTINA",
        "bonpland - ARGENTINA",
        "caa yari - ARGENTINA",
        "campo grande - ARGENTINA",
        "campo ramon - ARGENTINA",
        "campo viera - ARGENTINA",
        "candelaria - ARGENTINA",
        "capiovi - ARGENTINA",
        "caraguatay - ARGENTINA",
        "cdte. guacurari - ARGENTINA",
        "cerro azul - ARGENTINA",
        "cerro cora - ARGENTINA",
        "col. alberdi - ARGENTINA",
        "col. aurora - ARGENTINA",
        "col. delicia - ARGENTINA",
        "col. polana - ARGENTINA",
        "col. victoria - ARGENTINA",
        "col. wanda - ARGENTINA",
        "concepcion de la sierra - ARGENTINA",
        "corpus - ARGENTINA",
        "dos arroyos - ARGENTINA",
        "dos de mayo - ARGENTINA",
        "el alcazar - ARGENTINA",
        "el dorado - ARGENTINA",
        "el soberbio - ARGENTINA",
        "esperanza - ARGENTINA",
        "f. ameghino - ARGENTINA",
        "fachinal - ARGENTINA",
        "garuhape - ARGENTINA",
        "garupa - ARGENTINA",
        "gdor. lopez - ARGENTINA",
        "gdor. roca - ARGENTINA",
        "gral. alvear - ARGENTINA",
        "gral. urquiza - ARGENTINA",
        "guarani - ARGENTINA",
        "h. yrigoyen - ARGENTINA",
        "iguazu - ARGENTINA",
        "itacaruare - ARGENTINA",
        "jardin america - ARGENTINA",
        "leandro n. alem - ARGENTINA",
        "libertad - ARGENTINA",
        "loreto - ARGENTINA",
        "los helechos - ARGENTINA",
        "martires - ARGENTINA",
        "misiones - ARGENTINA",
        "mojon grande - ARGENTINA",
        "montecarlo - ARGENTINA",
        "nueve de julio - ARGENTINA",
        "obera - ARGENTINA",
        "olegario v. andrade - ARGENTINA",
        "panambi - ARGENTINA",
        "posadas - ARGENTINA",
        "profundidad - ARGENTINA",
        "pto. iguazu - ARGENTINA",
        "pto. leoni - ARGENTINA",
        "pto. piray - ARGENTINA",
        "pto. rico - ARGENTINA",
        "ruiz de montoya - ARGENTINA",
        "san antonio - ARGENTINA",
        "san ignacio - ARGENTINA",
        "san javier - ARGENTINA",
        "san jose - ARGENTINA",
        "san martin - ARGENTINA",
        "san pedro - ARGENTINA",
        "san vicente - ARGENTINA",
        "santiago de liniers - ARGENTINA",
        "santo pipo - ARGENTINA",
        "sta. ana - ARGENTINA",
        "sta. maria - ARGENTINA",
        "tres capones - ARGENTINA",
        "veinticinco de mayo - ARGENTINA",
        "wanda - ARGENTINA",
        "aguada san roque - ARGENTINA",
        "alumine - ARGENTINA",
        "andacollo - ARGENTINA",
        "anielo - ARGENTINA",
        "bajada del agrio - ARGENTINA",
        "barrancas - ARGENTINA",
        "buta ranquil - ARGENTINA",
        "capital - ARGENTINA",
        "caviahue - ARGENTINA",
        "centenario - ARGENTINA",
        "chorriaca - ARGENTINA",
        "chos malal - ARGENTINA",
        "cipolletti - ARGENTINA",
        "covunco abajo - ARGENTINA",
        "coyuco cochico - ARGENTINA",
        "cutral co - ARGENTINA",
        "el cholar - ARGENTINA",
        "el huecu - ARGENTINA",
        "el sauce - ARGENTINA",
        "guaniacos - ARGENTINA",
        "huinganco - ARGENTINA",
        "las coloradas - ARGENTINA",
        "las lajas - ARGENTINA",
        "las ovejas - ARGENTINA",
        "loncopue - ARGENTINA",
        "los catutos - ARGENTINA",
        "los chihuidos - ARGENTINA",
        "los miches - ARGENTINA",
        "manzano amargo - ARGENTINA",
        "neuquen - ARGENTINA",
        "octavio pico - ARGENTINA",
        "paso aguerre - ARGENTINA",
        "picun leufu - ARGENTINA",
        "piedra del aguila - ARGENTINA",
        "pilo lil - ARGENTINA",
        "plaza huincul - ARGENTINA",
        "plottier - ARGENTINA",
        "quili malal - ARGENTINA",
        "ramon castro - ARGENTINA",
        "rincon de los sauces - ARGENTINA",
        "san martin de los andes - ARGENTINA",
        "san patricio del chaniar - ARGENTINA",
        "santo tomas - ARGENTINA",
        "sauzal bonito - ARGENTINA",
        "senillosa - ARGENTINA",
        "taquimilan - ARGENTINA",
        "tricao malal - ARGENTINA",
        "varvarco - ARGENTINA",
        "villa curi leuvu - ARGENTINA",
        "villa del nahueve - ARGENTINA",
        "villa del puente picun leuvu - ARGENTINA",
        "villa el chocon - ARGENTINA",
        "villa la angostura - ARGENTINA",
        "villa pehuenia - ARGENTINA",
        "villa traful - ARGENTINA",
        "vista alegre - ARGENTINA",
        "zapala - ARGENTINA",
        "aguada cecilio - ARGENTINA",
        "aguada de guerra - ARGENTINA",
        "allen - ARGENTINA",
        "arroyo de la ventana - ARGENTINA",
        "arroyo los berros - ARGENTINA",
        "bariloche - ARGENTINA",
        "calte. cordero - ARGENTINA",
        "campo grande - ARGENTINA",
        "catriel - ARGENTINA",
        "cerro policia - ARGENTINA",
        "cervantes - ARGENTINA",
        "chelforo - ARGENTINA",
        "chimpay - ARGENTINA",
        "chinchinales - ARGENTINA",
        "chipauquil - ARGENTINA",
        "choele choel - ARGENTINA",
        "cinco saltos - ARGENTINA",
        "cipolletti - ARGENTINA",
        "clemente onelli - ARGENTINA",
        "colan conhue - ARGENTINA",
        "comallo - ARGENTINA",
        "comico - ARGENTINA",
        "cona niyeu - ARGENTINA",
        "coronel belisle - ARGENTINA",
        "cubanea - ARGENTINA",
        "darwin - ARGENTINA",
        "dina huapi - ARGENTINA",
        "el bolson - ARGENTINA",
        "el cain - ARGENTINA",
        "el manso - ARGENTINA",
        "gral. conesa - ARGENTINA",
        "gral. enrique godoy - ARGENTINA",
        "gral. fernandez oro - ARGENTINA",
        "gral. roca - ARGENTINA",
        "guardia mitre - ARGENTINA",
        "ing. huergo - ARGENTINA",
        "ing. jacobacci - ARGENTINA",
        "laguna blanca - ARGENTINA",
        "lamarque - ARGENTINA",
        "las grutas - ARGENTINA",
        "los menucos - ARGENTINA",
        "luis beltran - ARGENTINA",
        "mainque - ARGENTINA",
        "mamuel choique - ARGENTINA",
        "maquinchao - ARGENTINA",
        "mencue - ARGENTINA",
        "mtro. ramos mexia - ARGENTINA",
        "nahuel niyeu - ARGENTINA",
        "naupa huen - ARGENTINA",
        "niorquinco - ARGENTINA",
        "ojos de agua - ARGENTINA",
        "paso de agua - ARGENTINA",
        "paso flores - ARGENTINA",
        "penias blancas - ARGENTINA",
        "pichi mahuida - ARGENTINA",
        "pilcaniyeu - ARGENTINA",
        "pomona - ARGENTINA",
        "prahuaniyeu - ARGENTINA",
        "rincon treneta - ARGENTINA",
        "rio chico - ARGENTINA",
        "rio colorado - ARGENTINA",
        "roca - ARGENTINA",
        "san antonio oeste - ARGENTINA",
        "san javier - ARGENTINA",
        "sierra colorada - ARGENTINA",
        "sierra grande - ARGENTINA",
        "sierra paileman - ARGENTINA",
        "valcheta - ARGENTINA",
        "valle azul - ARGENTINA",
        "viedma - ARGENTINA",
        "villa llanquin - ARGENTINA",
        "villa mascardi - ARGENTINA",
        "villa regina - ARGENTINA",
        "yaminue - ARGENTINA",
        "a. saravia - ARGENTINA",
        "aguaray - ARGENTINA",
        "angastaco - ARGENTINA",
        "animana - ARGENTINA",
        "cachi - ARGENTINA",
        "cafayate - ARGENTINA",
        "campo quijano - ARGENTINA",
        "campo santo - ARGENTINA",
        "capital - ARGENTINA",
        "cerrillos - ARGENTINA",
        "chicoana - ARGENTINA",
        "col. sta. rosa - ARGENTINA",
        "coronel moldes - ARGENTINA",
        "el bordo - ARGENTINA",
        "el carril - ARGENTINA",
        "el galpon - ARGENTINA",
        "el jardin - ARGENTINA",
        "el potrero - ARGENTINA",
        "el quebrachal - ARGENTINA",
        "el tala - ARGENTINA",
        "embarcacion - ARGENTINA",
        "gral. ballivian - ARGENTINA",
        "gral. guemes - ARGENTINA",
        "gral. mosconi - ARGENTINA",
        "gral. pizarro - ARGENTINA",
        "guachipas - ARGENTINA",
        "hipolito yrigoyen - ARGENTINA",
        "iruya - ARGENTINA",
        "isla de canias - ARGENTINA",
        "j. v. gonzalez - ARGENTINA",
        "la caldera - ARGENTINA",
        "la candelaria - ARGENTINA",
        "la merced - ARGENTINA",
        "la poma - ARGENTINA",
        "la vinia - ARGENTINA",
        "las lajitas - ARGENTINA",
        "los toldos - ARGENTINA",
        "metan - ARGENTINA",
        "molinos - ARGENTINA",
        "nazareno - ARGENTINA",
        "oran - ARGENTINA",
        "payogasta - ARGENTINA",
        "pichanal - ARGENTINA",
        "prof. s. mazza - ARGENTINA",
        "rio piedras - ARGENTINA",
        "rivadavia banda norte - ARGENTINA",
        "rivadavia banda sur - ARGENTINA",
        "rosario de la frontera - ARGENTINA",
        "rosario de lerma - ARGENTINA",
        "saclantas - ARGENTINA",
        "salta - ARGENTINA",
        "san antonio - ARGENTINA",
        "san carlos - ARGENTINA",
        "san jose de metan - ARGENTINA",
        "san ramon - ARGENTINA",
        "santa victoria e. - ARGENTINA",
        "santa victoria o. - ARGENTINA",
        "tartagal - ARGENTINA",
        "tolar grande - ARGENTINA",
        "urundel - ARGENTINA",
        "vaqueros - ARGENTINA",
        "villa san lorenzo - ARGENTINA",
        "albardon - ARGENTINA",
        "angaco - ARGENTINA",
        "calingasta - ARGENTINA",
        "capital - ARGENTINA",
        "caucete - ARGENTINA",
        "chimbas - ARGENTINA",
        "iglesia - ARGENTINA",
        "jachal - ARGENTINA",
        "nueve de julio - ARGENTINA",
        "pocito - ARGENTINA",
        "rawson - ARGENTINA",
        "rivadavia - ARGENTINA",
        "san juan - ARGENTINA",
        "san martin - ARGENTINA",
        "santa lucia - ARGENTINA",
        "sarmiento - ARGENTINA",
        "ullum - ARGENTINA",
        "valle fertil - ARGENTINA",
        "veinticinco de mayo - ARGENTINA",
        "zonda - ARGENTINA",
        "alto pelado - ARGENTINA",
        "alto pencoso - ARGENTINA",
        "anchorena - ARGENTINA",
        "arizona - ARGENTINA",
        "bagual - ARGENTINA",
        "balde - ARGENTINA",
        "batavia - ARGENTINA",
        "beazley - ARGENTINA",
        "buena esperanza - ARGENTINA",
        "candelaria - ARGENTINA",
        "capital - ARGENTINA",
        "carolina - ARGENTINA",
        "carpinteria - ARGENTINA",
        "concaran - ARGENTINA",
        "cortaderas - ARGENTINA",
        "el morro - ARGENTINA",
        "el trapiche - ARGENTINA",
        "el volcan - ARGENTINA",
        "fortin el patria - ARGENTINA",
        "fortuna - ARGENTINA",
        "fraga - ARGENTINA",
        "juan jorba - ARGENTINA",
        "juan llerena - ARGENTINA",
        "juana koslay - ARGENTINA",
        "justo daract - ARGENTINA",
        "la calera - ARGENTINA",
        "la florida - ARGENTINA",
        "la punilla - ARGENTINA",
        "la toma - ARGENTINA",
        "lafinur - ARGENTINA",
        "las aguadas - ARGENTINA",
        "las chacras - ARGENTINA",
        "las lagunas - ARGENTINA",
        "las vertientes - ARGENTINA",
        "lavaisse - ARGENTINA",
        "leandro n. alem - ARGENTINA",
        "los molles - ARGENTINA",
        "lujan - ARGENTINA",
        "mercedes - ARGENTINA",
        "merlo - ARGENTINA",
        "naschel - ARGENTINA",
        "navia - ARGENTINA",
        "nogoli - ARGENTINA",
        "nueva galia - ARGENTINA",
        "papagayos - ARGENTINA",
        "paso grande - ARGENTINA",
        "potrero de los funes - ARGENTINA",
        "quines - ARGENTINA",
        "renca - ARGENTINA",
        "saladillo - ARGENTINA",
        "san francisco - ARGENTINA",
        "san geronimo - ARGENTINA",
        "san martin - ARGENTINA",
        "san pablo - ARGENTINA",
        "santa rosa de conlara - ARGENTINA",
        "talita - ARGENTINA",
        "tilisarao - ARGENTINA",
        "union - ARGENTINA",
        "villa de la quebrada - ARGENTINA",
        "villa de praga - ARGENTINA",
        "villa del carmen - ARGENTINA",
        "villa gral. roca - ARGENTINA",
        "villa larca - ARGENTINA",
        "villa mercedes - ARGENTINA",
        "zanjitas - ARGENTINA",
        "calafate - ARGENTINA",
        "caleta olivia - ARGENTINA",
        "caniadon seco - ARGENTINA",
        "comandante piedrabuena - ARGENTINA",
        "el calafate - ARGENTINA",
        "el chalten - ARGENTINA",
        "gdor. gregores - ARGENTINA",
        "hipolito yrigoyen - ARGENTINA",
        "jaramillo - ARGENTINA",
        "koluel kaike - ARGENTINA",
        "las heras - ARGENTINA",
        "los antiguos - ARGENTINA",
        "perito moreno - ARGENTINA",
        "pico truncado - ARGENTINA",
        "pto. deseado - ARGENTINA",
        "pto. san julian - ARGENTINA",
        "pto. santa cruz - ARGENTINA",
        "rio cuarto - ARGENTINA",
        "rio gallegos - ARGENTINA",
        "rio turbio - ARGENTINA",
        "tres lagos - ARGENTINA",
        "veintiocho de noviembre - ARGENTINA",
        "aaron castellanos - ARGENTINA",
        "acebal - ARGENTINA",
        "aguara grande - ARGENTINA",
        "albarellos - ARGENTINA",
        "alcorta - ARGENTINA",
        "aldao - ARGENTINA",
        "alejandra - ARGENTINA",
        "alvarez - ARGENTINA",
        "ambrosetti - ARGENTINA",
        "amenabar - ARGENTINA",
        "angelica - ARGENTINA",
        "angeloni - ARGENTINA",
        "arequito - ARGENTINA",
        "arminda - ARGENTINA",
        "armstrong - ARGENTINA",
        "arocena - ARGENTINA",
        "arroyo aguiar - ARGENTINA",
        "arroyo ceibal - ARGENTINA",
        "arroyo leyes - ARGENTINA",
        "arroyo seco - ARGENTINA",
        "arrufo - ARGENTINA",
        "arteaga - ARGENTINA",
        "ataliva - ARGENTINA",
        "aurelia - ARGENTINA",
        "avellaneda - ARGENTINA",
        "barrancas - ARGENTINA",
        "bauer y sigel - ARGENTINA",
        "bella italia - ARGENTINA",
        "berabevu - ARGENTINA",
        "berna - ARGENTINA",
        "bernardo de irigoyen - ARGENTINA",
        "bigand - ARGENTINA",
        "bombal - ARGENTINA",
        "bouquet - ARGENTINA",
        "bustinza - ARGENTINA",
        "cabal - ARGENTINA",
        "cacique ariacaiquin - ARGENTINA",
        "cafferata - ARGENTINA",
        "calchaqui - ARGENTINA",
        "campo andino - ARGENTINA",
        "campo piaggio - ARGENTINA",
        "caniada de gomez - ARGENTINA",
        "caniada del ucle - ARGENTINA",
        "caniada rica - ARGENTINA",
        "caniada rosquin - ARGENTINA",
        "candioti - ARGENTINA",
        "capital - ARGENTINA",
        "capitan bermudez - ARGENTINA",
        "capivara - ARGENTINA",
        "carcarania - ARGENTINA",
        "carlos pellegrini - ARGENTINA",
        "carmen - ARGENTINA",
        "carmen del sauce - ARGENTINA",
        "carreras - ARGENTINA",
        "carrizales - ARGENTINA",
        "casalegno - ARGENTINA",
        "casas - ARGENTINA",
        "casilda - ARGENTINA",
        "castelar - ARGENTINA",
        "castellanos - ARGENTINA",
        "cayasta - ARGENTINA",
        "cayastacito - ARGENTINA",
        "centeno - ARGENTINA",
        "cepeda - ARGENTINA",
        "ceres - ARGENTINA",
        "chabas - ARGENTINA",
        "chaniar ladeado - ARGENTINA",
        "chapuy - ARGENTINA",
        "chovet - ARGENTINA",
        "christophersen - ARGENTINA",
        "classon - ARGENTINA",
        "cnel. arnold - ARGENTINA",
        "cnel. bogado - ARGENTINA",
        "cnel. dominguez - ARGENTINA",
        "cnel. fraga - ARGENTINA",
        "col. aldao - ARGENTINA",
        "col. ana - ARGENTINA",
        "col. belgrano - ARGENTINA",
        "col. bicha - ARGENTINA",
        "col. bigand - ARGENTINA",
        "col. bossi - ARGENTINA",
        "col. cavour - ARGENTINA",
        "col. cello - ARGENTINA",
        "col. dolores - ARGENTINA",
        "col. dos rosas - ARGENTINA",
        "col. duran - ARGENTINA",
        "col. iturraspe - ARGENTINA",
        "col. margarita - ARGENTINA",
        "col. mascias - ARGENTINA",
        "col. raquel - ARGENTINA",
        "col. rosa - ARGENTINA",
        "col. san jose - ARGENTINA",
        "constanza - ARGENTINA",
        "coronda - ARGENTINA",
        "correa - ARGENTINA",
        "crispi - ARGENTINA",
        "cululu - ARGENTINA",
        "curupayti - ARGENTINA",
        "desvio arijon - ARGENTINA",
        "diaz - ARGENTINA",
        "diego de alvear - ARGENTINA",
        "egusquiza - ARGENTINA",
        "el araza - ARGENTINA",
        "el rabon - ARGENTINA",
        "el sombrerito - ARGENTINA",
        "el trebol - ARGENTINA",
        "elisa - ARGENTINA",
        "elortondo - ARGENTINA",
        "emilia - ARGENTINA",
        "empalme san carlos - ARGENTINA",
        "empalme villa constitucion - ARGENTINA",
        "esmeralda - ARGENTINA",
        "esperanza - ARGENTINA",
        "estacion alvear - ARGENTINA",
        "estacion clucellas - ARGENTINA",
        "esteban rams - ARGENTINA",
        "esther - ARGENTINA",
        "esustolia - ARGENTINA",
        "eusebia - ARGENTINA",
        "felicia - ARGENTINA",
        "fidela - ARGENTINA",
        "fighiera - ARGENTINA",
        "firmat - ARGENTINA",
        "florencia - ARGENTINA",
        "fortin olmos - ARGENTINA",
        "franck - ARGENTINA",
        "fray luis beltran - ARGENTINA",
        "frontera - ARGENTINA",
        "fuentes - ARGENTINA",
        "funes - ARGENTINA",
        "gaboto - ARGENTINA",
        "galisteo - ARGENTINA",
        "galvez - ARGENTINA",
        "garabalto - ARGENTINA",
        "garibaldi - ARGENTINA",
        "gato colorado - ARGENTINA",
        "gdor. crespo - ARGENTINA",
        "gessler - ARGENTINA",
        "godoy - ARGENTINA",
        "golondrina - ARGENTINA",
        "gral. gelly - ARGENTINA",
        "gral. lagos - ARGENTINA",
        "granadero baigorria - ARGENTINA",
        "gregoria perez de denis - ARGENTINA",
        "grutly - ARGENTINA",
        "guadalupe n. - ARGENTINA",
        "g?deken - ARGENTINA",
        "helvecia - ARGENTINA",
        "hersilia - ARGENTINA",
        "hipatia - ARGENTINA",
        "huanqueros - ARGENTINA",
        "hugentobler - ARGENTINA",
        "hughes - ARGENTINA",
        "humberto 1 - ARGENTINA",
        "humboldt - ARGENTINA",
        "ibarlucea - ARGENTINA",
        "ing. chanourdie - ARGENTINA",
        "intiyaco - ARGENTINA",
        "ituzaingo - ARGENTINA",
        "jacinto l. arauz - ARGENTINA",
        "josefina - ARGENTINA",
        "juan b. molina - ARGENTINA",
        "juan de garay - ARGENTINA",
        "juncal - ARGENTINA",
        "la brava - ARGENTINA",
        "la cabral - ARGENTINA",
        "la camila - ARGENTINA",
        "la chispa - ARGENTINA",
        "la clara - ARGENTINA",
        "la criolla - ARGENTINA",
        "la gallareta - ARGENTINA",
        "la lucila - ARGENTINA",
        "la pelada - ARGENTINA",
        "la penca - ARGENTINA",
        "la rubia - ARGENTINA",
        "la sarita - ARGENTINA",
        "la vanguardia - ARGENTINA",
        "labordeboy - ARGENTINA",
        "laguna paiva - ARGENTINA",
        "landeta - ARGENTINA",
        "lanteri - ARGENTINA",
        "larrechea - ARGENTINA",
        "las avispas - ARGENTINA",
        "las bandurrias - ARGENTINA",
        "las garzas - ARGENTINA",
        "las palmeras - ARGENTINA",
        "las parejas - ARGENTINA",
        "las petacas - ARGENTINA",
        "las rosas - ARGENTINA",
        "las toscas - ARGENTINA",
        "las tunas - ARGENTINA",
        "lazzarino - ARGENTINA",
        "lehmann - ARGENTINA",
        "llambi campbell - ARGENTINA",
        "logronio - ARGENTINA",
        "loma alta - ARGENTINA",
        "lopez - ARGENTINA",
        "los amores - ARGENTINA",
        "los cardos - ARGENTINA",
        "los laureles - ARGENTINA",
        "los molinos - ARGENTINA",
        "los quirquinchos - ARGENTINA",
        "lucio v. lopez - ARGENTINA",
        "luis palacios - ARGENTINA",
        "ma. juana - ARGENTINA",
        "ma. luisa - ARGENTINA",
        "ma. susana - ARGENTINA",
        "ma. teresa - ARGENTINA",
        "maciel - ARGENTINA",
        "maggiolo - ARGENTINA",
        "malabrigo - ARGENTINA",
        "marcelino escalada - ARGENTINA",
        "margarita - ARGENTINA",
        "matilde - ARGENTINA",
        "maua - ARGENTINA",
        "maximo paz - ARGENTINA",
        "melincue - ARGENTINA",
        "miguel torres - ARGENTINA",
        "moises ville - ARGENTINA",
        "monigotes - ARGENTINA",
        "monje - ARGENTINA",
        "monte obscuridad - ARGENTINA",
        "monte vera - ARGENTINA",
        "montefiore - ARGENTINA",
        "montes de oca - ARGENTINA",
        "murphy - ARGENTINA",
        "nianducita - ARGENTINA",
        "nare - ARGENTINA",
        "nelson - ARGENTINA",
        "nicanor e. molinas - ARGENTINA",
        "nuevo torino - ARGENTINA",
        "oliveros - ARGENTINA",
        "palacios - ARGENTINA",
        "pavon - ARGENTINA",
        "pavon arriba - ARGENTINA",
        "pedro gomez cello - ARGENTINA",
        "perez - ARGENTINA",
        "peyrano - ARGENTINA",
        "piamonte - ARGENTINA",
        "pilar - ARGENTINA",
        "piniero - ARGENTINA",
        "plaza clucellas - ARGENTINA",
        "portugalete - ARGENTINA",
        "pozo borrado - ARGENTINA",
        "progreso - ARGENTINA",
        "providencia - ARGENTINA",
        "pte. roca - ARGENTINA",
        "pueblo andino - ARGENTINA",
        "pueblo esther - ARGENTINA",
        "pueblo gral. san martin - ARGENTINA",
        "pueblo irigoyen - ARGENTINA",
        "pueblo marini - ARGENTINA",
        "pueblo munioz - ARGENTINA",
        "pueblo uranga - ARGENTINA",
        "pujato - ARGENTINA",
        "pujato n. - ARGENTINA",
        "rafaela - ARGENTINA",
        "ramayon - ARGENTINA",
        "ramona - ARGENTINA",
        "reconquista - ARGENTINA",
        "recreo - ARGENTINA",
        "ricardone - ARGENTINA",
        "rivadavia - ARGENTINA",
        "roldan - ARGENTINA",
        "romang - ARGENTINA",
        "rosario - ARGENTINA",
        "rueda - ARGENTINA",
        "rufino - ARGENTINA",
        "sa pereira - ARGENTINA",
        "saguier - ARGENTINA",
        "saladero m. cabal - ARGENTINA",
        "salto grande - ARGENTINA",
        "san agustin - ARGENTINA",
        "san antonio de obligado - ARGENTINA",
        "san bernardo n.j. - ARGENTINA",
        "san bernardo s.j. - ARGENTINA",
        "san carlos centro - ARGENTINA",
        "san carlos n. - ARGENTINA",
        "san carlos s. - ARGENTINA",
        "san cristobal - ARGENTINA",
        "san eduardo - ARGENTINA",
        "san eugenio - ARGENTINA",
        "san fabian - ARGENTINA",
        "san fco. de santa fe - ARGENTINA",
        "san genaro - ARGENTINA",
        "san genaro n. - ARGENTINA",
        "san gregorio - ARGENTINA",
        "san guillermo - ARGENTINA",
        "san javier - ARGENTINA",
        "san jeronimo del sauce - ARGENTINA",
        "san jeronimo n. - ARGENTINA",
        "san jeronimo s. - ARGENTINA",
        "san jorge - ARGENTINA",
        "san jose de la esquina - ARGENTINA",
        "san jose del rincon - ARGENTINA",
        "san justo - ARGENTINA",
        "san lorenzo - ARGENTINA",
        "san mariano - ARGENTINA",
        "san martin de las escobas - ARGENTINA",
        "san martin n. - ARGENTINA",
        "san vicente - ARGENTINA",
        "sancti spititu - ARGENTINA",
        "sanford - ARGENTINA",
        "santo domingo - ARGENTINA",
        "santo tome - ARGENTINA",
        "santurce - ARGENTINA",
        "sargento cabral - ARGENTINA",
        "sarmiento - ARGENTINA",
        "sastre - ARGENTINA",
        "sauce viejo - ARGENTINA",
        "serodino - ARGENTINA",
        "silva - ARGENTINA",
        "soldini - ARGENTINA",
        "soledad - ARGENTINA",
        "soutomayor - ARGENTINA",
        "sta. clara de buena vista - ARGENTINA",
        "sta. clara de saguier - ARGENTINA",
        "sta. isabel - ARGENTINA",
        "sta. margarita - ARGENTINA",
        "sta. maria centro - ARGENTINA",
        "sta. maria n. - ARGENTINA",
        "sta. rosa - ARGENTINA",
        "sta. teresa - ARGENTINA",
        "suardi - ARGENTINA",
        "sunchales - ARGENTINA",
        "susana - ARGENTINA",
        "tacuarendi - ARGENTINA",
        "tacural - ARGENTINA",
        "tartagal - ARGENTINA",
        "teodelina - ARGENTINA",
        "theobald - ARGENTINA",
        "timbues - ARGENTINA",
        "toba - ARGENTINA",
        "tortugas - ARGENTINA",
        "tostado - ARGENTINA",
        "totoras - ARGENTINA",
        "traill - ARGENTINA",
        "venado tuerto - ARGENTINA",
        "vera - ARGENTINA",
        "vera y pintado - ARGENTINA",
        "videla - ARGENTINA",
        "vila - ARGENTINA",
        "villa amelia - ARGENTINA",
        "villa ana - ARGENTINA",
        "villa canias - ARGENTINA",
        "villa constitucion - ARGENTINA",
        "villa eloisa - ARGENTINA",
        "villa gdor. galvez - ARGENTINA",
        "villa guillermina - ARGENTINA",
        "villa minetti - ARGENTINA",
        "villa mugueta - ARGENTINA",
        "villa ocampo - ARGENTINA",
        "villa san jose - ARGENTINA",
        "villa saralegui - ARGENTINA",
        "villa trinidad - ARGENTINA",
        "villada - ARGENTINA",
        "virginia - ARGENTINA",
        "wheelwright - ARGENTINA",
        "zavalla - ARGENTINA",
        "zenon pereira - ARGENTINA",
        "aniatuya - ARGENTINA",
        "arraga - ARGENTINA",
        "bandera - ARGENTINA",
        "bandera bajada - ARGENTINA",
        "beltran - ARGENTINA",
        "brea pozo - ARGENTINA",
        "campo gallo - ARGENTINA",
        "capital - ARGENTINA",
        "chilca juliana - ARGENTINA",
        "choya - ARGENTINA",
        "clodomira - ARGENTINA",
        "col. alpina - ARGENTINA",
        "col. dora - ARGENTINA",
        "col. el simbolar robles - ARGENTINA",
        "el bobadal - ARGENTINA",
        "el charco - ARGENTINA",
        "el mojon - ARGENTINA",
        "estacion atamisqui - ARGENTINA",
        "estacion simbolar - ARGENTINA",
        "fernandez - ARGENTINA",
        "fortin inca - ARGENTINA",
        "frias - ARGENTINA",
        "garza - ARGENTINA",
        "gramilla - ARGENTINA",
        "guardia escolta - ARGENTINA",
        "herrera - ARGENTINA",
        "icanio - ARGENTINA",
        "ing. forres - ARGENTINA",
        "la banda - ARGENTINA",
        "la caniada - ARGENTINA",
        "laprida - ARGENTINA",
        "lavalle - ARGENTINA",
        "loreto - ARGENTINA",
        "los juries - ARGENTINA",
        "los nuniez - ARGENTINA",
        "los pirpintos - ARGENTINA",
        "los quiroga - ARGENTINA",
        "los telares - ARGENTINA",
        "lugones - ARGENTINA",
        "malbran - ARGENTINA",
        "matara - ARGENTINA",
        "medellin - ARGENTINA",
        "monte quemado - ARGENTINA",
        "nueva esperanza - ARGENTINA",
        "nueva francia - ARGENTINA",
        "palo negro - ARGENTINA",
        "pampa de los guanacos - ARGENTINA",
        "pinto - ARGENTINA",
        "pozo hondo - ARGENTINA",
        "quimili - ARGENTINA",
        "real sayana - ARGENTINA",
        "sachayoj - ARGENTINA",
        "san pedro de guasayan - ARGENTINA",
        "selva - ARGENTINA",
        "sol de julio - ARGENTINA",
        "sumampa - ARGENTINA",
        "suncho corral - ARGENTINA",
        "taboada - ARGENTINA",
        "tapso - ARGENTINA",
        "termas de rio hondo - ARGENTINA",
        "tintina - ARGENTINA",
        "tomas young - ARGENTINA",
        "vilelas - ARGENTINA",
        "villa atamisqui - ARGENTINA",
        "villa la punta - ARGENTINA",
        "villa ojo de agua - ARGENTINA",
        "villa rio hondo - ARGENTINA",
        "villa salavina - ARGENTINA",
        "villa union - ARGENTINA",
        "vilmer - ARGENTINA",
        "weisburd - ARGENTINA",
        "rio grande - ARGENTINA",
        "tolhuin - ARGENTINA",
        "ushuaia - ARGENTINA",
        "acheral - ARGENTINA",
        "agua dulce - ARGENTINA",
        "aguilares - ARGENTINA",
        "alderetes - ARGENTINA",
        "alpachiri - ARGENTINA",
        "alto verde - ARGENTINA",
        "amaicha del valle - ARGENTINA",
        "amberes - ARGENTINA",
        "ancajuli - ARGENTINA",
        "arcadia - ARGENTINA",
        "atahona - ARGENTINA",
        "banda del rio sali - ARGENTINA",
        "bella vista - ARGENTINA",
        "buena vista - ARGENTINA",
        "burruyacu - ARGENTINA",
        "capitan caceres - ARGENTINA",
        "cevil redondo - ARGENTINA",
        "choromoro - ARGENTINA",
        "ciudacita - ARGENTINA",
        "colalao del valle - ARGENTINA",
        "colombres - ARGENTINA",
        "concepcion - ARGENTINA",
        "delfin gallo - ARGENTINA",
        "el bracho - ARGENTINA",
        "el cadillal - ARGENTINA",
        "el cercado - ARGENTINA",
        "el chaniar - ARGENTINA",
        "el manantial - ARGENTINA",
        "el mojon - ARGENTINA",
        "el mollar - ARGENTINA",
        "el naranjito - ARGENTINA",
        "el naranjo - ARGENTINA",
        "el polear - ARGENTINA",
        "el puestito - ARGENTINA",
        "el sacrificio - ARGENTINA",
        "el timbo - ARGENTINA",
        "escaba - ARGENTINA",
        "esquina - ARGENTINA",
        "estacion araoz - ARGENTINA",
        "famailla - ARGENTINA",
        "gastone - ARGENTINA",
        "gdor. garmendia - ARGENTINA",
        "gdor. piedrabuena - ARGENTINA",
        "graneros - ARGENTINA",
        "huasa pampa - ARGENTINA",
        "j. b. alberdi - ARGENTINA",
        "la cocha - ARGENTINA",
        "la esperanza - ARGENTINA",
        "la florida - ARGENTINA",
        "la ramada - ARGENTINA",
        "la trinidad - ARGENTINA",
        "lamadrid - ARGENTINA",
        "las cejas - ARGENTINA",
        "las talas - ARGENTINA",
        "las talitas - ARGENTINA",
        "los bulacio - ARGENTINA",
        "los gomez - ARGENTINA",
        "los nogales - ARGENTINA",
        "los pereyra - ARGENTINA",
        "los perez - ARGENTINA",
        "los puestos - ARGENTINA",
        "los ralos - ARGENTINA",
        "los sarmientos - ARGENTINA",
        "los sosa - ARGENTINA",
        "lules - ARGENTINA",
        "m. garcia fernandez - ARGENTINA",
        "manuela pedraza - ARGENTINA",
        "medinas - ARGENTINA",
        "monte bello - ARGENTINA",
        "monteagudo - ARGENTINA",
        "monteros - ARGENTINA",
        "padre monti - ARGENTINA",
        "pampa mayo - ARGENTINA",
        "quilmes - ARGENTINA",
        "raco - ARGENTINA",
        "ranchillos - ARGENTINA",
        "rio chico - ARGENTINA",
        "rio colorado - ARGENTINA",
        "rio seco - ARGENTINA",
        "rumi punco - ARGENTINA",
        "san andres - ARGENTINA",
        "san felipe - ARGENTINA",
        "san ignacio - ARGENTINA",
        "san javier - ARGENTINA",
        "san jose - ARGENTINA",
        "san miguel de tucuman - ARGENTINA",
        "san pedro - ARGENTINA",
        "san pedro de colalao - ARGENTINA",
        "santa rosa de leales - ARGENTINA",
        "sgto. moya - ARGENTINA",
        "siete de abril - ARGENTINA",
        "simoca - ARGENTINA",
        "soldado maldonado - ARGENTINA",
        "sta. ana - ARGENTINA",
        "sta. cruz - ARGENTINA",
        "sta. lucia - ARGENTINA",
        "taco ralo - ARGENTINA",
        "tafi del valle - ARGENTINA",
        "tafi viejo - ARGENTINA",
        "tapia - ARGENTINA",
        "teniente berdina - ARGENTINA",
        "trancas - ARGENTINA",
        "villa belgrano - ARGENTINA",
        "villa benjamin araoz - ARGENTINA",
        "villa chiligasta - ARGENTINA",
        "villa de leales - ARGENTINA",
        "villa quinteros - ARGENTINA",
        "yanima - ARGENTINA",
        "yerba buena - ARGENTINA",
        "yerba buena s - ARGENTINA"
    ]
        
        self.style = ttk.Style()
        self.style.configure('TFrame', background='#f0f0f0')
        self.style.configure('Header.TLabel', 
                           font=('Helvetica', 16, 'bold'), 
                           background='#f0f0f0',
                           padding=10)
        self.style.configure('Status.TLabel', 
                           background='#f0f0f0',
                           padding=5)
        
        self.create_widgets()
        
    def create_widgets(self):
        main_frame = ttk.Frame(self.root, padding="20")
        main_frame.pack(fill=tk.BOTH, expand=True)
        
        header_label = ttk.Label(
            main_frame, 
            text="John Deere Dealer Locator",
            style='Header.TLabel'
        )
        header_label.pack(pady=(0, 20))
        
        logo_frame = ttk.Frame(main_frame)
        logo_frame.pack(pady=10)
        logo_label = ttk.Label(
            logo_frame,
            text="🚜",
            font=('Helvetica', 48)
        )
        logo_label.pack()
        
        self.status_frame = ttk.Frame(main_frame)
        self.status_frame.pack(fill=tk.X, pady=20)
        
        self.status_label = ttk.Label(
            self.status_frame,
            text="Pronto para iniciar a extração",
            style='Status.TLabel'
        )
        self.status_label.pack()
        
        self.progress = ttk.Progressbar(
            main_frame,
            orient="horizontal",
            length=400,
            mode="indeterminate"
        )
        self.progress.pack(pady=20)
        
        button_frame = ttk.Frame(main_frame)
        button_frame.pack(pady=20)
        
        self.start_button = ttk.Button(
            button_frame,
            text="Iniciar Extração",
            command=self.start_scraping_thread,
            padding=(20, 1)
        )
        self.start_button.pack(side=tk.LEFT, padx=10)
        
        self.exit_button = ttk.Button(
            button_frame,
            text="Sair",
            command=self.root.quit,
            padding=(20, 1)
        )
        self.exit_button.pack(side=tk.LEFT, padx=10)

    def update_status(self, message):
        self.status_label.config(text=message)
        self.root.update()

    def start_scraping_thread(self):
        thread = threading.Thread(target=self.run_scraper)
        thread.daemon = True
        thread.start()

    def run_scraper(self):
        self.start_button.config(state='disabled')
        self.progress.start()
        self.update_status("Selecionando local para salvar arquivo CSV...")
        
        output_file = filedialog.asksaveasfilename(
            title="Selecione o local para salvar o arquivo CSV",
            defaultextension=".csv",
            filetypes=[("CSV files", "*.csv")]
        )
        if not output_file:
            self.reset_ui("Operação cancelada.")
            return
            
        self.update_status("Selecionando ChromeDriver...")
        driver_path = filedialog.askopenfilename(
            title="Selecione o executável do ChromeDriver",
            filetypes=[("Executável", "*.exe")]
        )
        if not driver_path:
            self.reset_ui("ChromeDriver não selecionado.")
            return
            
        self.update_status("Selecionando Google Chrome (opcional)...")
        chrome_path = filedialog.askopenfilename(
            title="Selecione o executável do Google Chrome (Opcional)",
            filetypes=[("Executável", "*.exe")]
        )
        
        try:
            self.update_status("Iniciando o navegador...")
            options = webdriver.ChromeOptions()
            if chrome_path:
                options.binary_location = chrome_path
            
            service = Service(driver_path)
            driver = webdriver.Chrome(service=service, options=options)
            driver.get("https://dealerlocator.deere.com/servlet/country=BR")
            time.sleep(2)
            
            unique_entries = set()
            
            with open(output_file, mode="w", newline="", encoding="utf-8") as file:
                writer = csv.writer(file)
                writer.writerow(["Dealer", "Endereço 1", "Endereço 2"])
                
                self.update_status(f"Processando cidade inicial: {self.listadecidades[0]}")
                self.process_first_city(driver)
                
                for index, cidade in enumerate(self.listadecidades):
                    self.update_status(f"Processando cidade: {cidade} {index}")
                    try:
                        self.process_city(driver, cidade, writer, unique_entries)
                        self.ensure_continue(driver)
                    except Exception as e:
                        self.update_status(f"Erro ao processar {cidade}: {str(e)}")
                        continue
                    if index > 0 and index % 5 == 0:
                        self.update_status("Reiniciando navegador para evitar travamentos...")
                        driver.quit()
                        driver = webdriver.Chrome(service=service, options=options)
                        driver.get("https://dealerlocator.deere.com/servlet/country=BR")
                        time.sleep(2)
                        self.process_first_city(driver)
            
            driver.quit()
            self.reset_ui("Extração concluída com sucesso!")
            messagebox.showinfo("Sucesso", "A extração foi concluída com sucesso!")
            
        except Exception as e:
            self.reset_ui(f"Erro durante a execução: {str(e)}")
            messagebox.showerror("Erro", f"Ocorreu um erro durante a execução: {e}")

    def process_first_city(self, driver):
        entrada = WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((By.XPATH, '//*[@id="google-page-level-search2"]'))
        )
        entrada.send_keys(self.listadecidades[0])
        
        submit = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.XPATH, '//*[@id="submit-form11"]'))
        )
        submit.click()
        
        tile = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.XPATH, '//div[@class="tiles"]//span[text()="Agricultura"]'))
        )
        tile.click()
        
        findDealer = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.XPATH, '//button[@class="btn btn-primary" and text()="Encontrar Concessionários"]'))
        )
        findDealer.click()

    def process_city(self, driver, cidade, writer, unique_entries):
        WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((By.XPATH, "//div[@class='list-wrap-background']"))
        )
        
        html = driver.page_source
        soup = BeautifulSoup(html, 'html.parser')
        results = soup.find_all("div", class_="list-wrap-background")
        
        if not results:
            self.update_status(f"Nenhum resultado encontrado para {cidade}")
        else:
            for result in results:
                dealer_name_div = result.find("div", class_="dealer-name")
                dealer_name = dealer_name_div.find("h5").text.strip() if dealer_name_div else "Nome não encontrado"
                
                address_divs = result.find_all("div", class_="address")
                endereco1 = address_divs[0].text.strip() if len(address_divs) > 0 else ""
                endereco2 = address_divs[1].text.strip() if len(address_divs) > 1 else ""
                endereco3 = address_divs[2].text.strip() if len(address_divs) > 2 else ""
                
                if endereco3:
                    endereco2 = f"{endereco2}, {endereco3}" if endereco2 else endereco3
                
                entry_key = (dealer_name, endereco1)
                if entry_key not in unique_entries:
                    unique_entries.add(entry_key)
                    writer.writerow([dealer_name, endereco1, endereco2])
        
        entrada = WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((By.XPATH, "//input[@id='google-page-level-search3']"))
        )
        entrada.send_keys(Keys.CONTROL + "a")
        entrada.send_keys(Keys.DELETE)
        entrada.send_keys(cidade)
        
        submit = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.XPATH, '//*[@id="submit-form11"]'))
        )
        submit.click()
        
        try:
            WebDriverWait(driver, 2).until(
                EC.presence_of_element_located(
                    (By.XPATH, '//div[contains(@class, "error-sms") and contains(text(), "Oops!")]')
                )
            )
            self.update_status(f"Erro detectado para {cidade}. Tentando novamente...")
            retry_button = WebDriverWait(driver, 1).until(
                EC.element_to_be_clickable((By.XPATH, '//*[@id="submit-form11"]'))
            )
            retry_button.click()
        except TimeoutException:
            pass
        
        WebDriverWait(driver, 1).until(
            EC.presence_of_element_located((By.XPATH, "//div[@class='list-wrap-background']"))
        )

    def reset_ui(self, status_message):
        self.progress.stop()
        self.start_button.config(state='normal')
        self.update_status(status_message)
        
    def run(self):
        self.root.mainloop()

if __name__ == "__main__":
    app = DealerLocatorApp()
    app.run()